### ISSUE TITLE
[Question] Logging all SQL Queries

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#104]
We are using casbin-gorm-adapter for our policies storage to DB
I would like to log all the queries that are fired to the DB.
How can I do that?

Previously when using the pg-adapter I was suggested to use the `go-pg` query hook for this purpose at https://github.com/casbin/casbin-pg-adapter/issues/20#issuecomment-779723037

I am looking for something similar in gorm-adapter

Note : We are using AWS EDS, so configuring Postgres to log statements to stdout isn't an option

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@arafat-java https://gorm.io/docs/logger.html + https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L164
Does this meet your requirement?

**Comment by arafat-java** [comment]
@closetool, I'll need to change the way I create the adapter. Will try this.
Any other alternatives ?
