### ISSUE TITLE
[QUESTION] - How Would I make queries for different scenarios

### ISSUE THREAD

**Issue by sujit-baniya** [casbin/gorm-adapter#108]
I've been using this adapter on Postgres. Curently I'm stuck on getting some information from Casbin. Please help me understand how could I query to get those information.

I'm trying to look for
1) If the domain is `*`, get all users associated to all domains with their respective roles
2) get all users associated to a domain with their respective roles

So I have basically added three roles: admin, account-admin, and user
admin  => with all powers
account-admin => with all powers for account (domain)
user => normal users

And Admin would see all users irrespective of domains, Account Admin would see all users associated with  the domain.

Currently I needed to make custom queries to fetch such information. Any help would be highly appreciated.

**Comment by hsluoyz** [comment]
@sujit-baniya plz use: https://casbin.org/docs/en/rbac-with-domains

**Comment by sujit-baniya** [comment]
@hsluoyz Thanks for your response. I added the extra matcher parameter but still I don't see any effect. Need to check more.

```conf
[request_definition]
r = sub, dom, obj, act

[policy_definition]
p = sub, dom, obj, act

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub, r.dom) && r.dom == p.dom && r.obj == p.obj && r.act == p.act || r.sub == root
```

**Comment by hsluoyz** [comment]
@sujit-baniya see: https://casbin.org/docs/en/rbac#use-pattern-matching-in-rbac

**Comment by sujit-baniya** [comment]
@hsluoyz Thanks again :). I tried and now I could get all Domains associated with the Admin account. Still casbin is not providing any API for getting all users for a Domain. Creating one issue on Casbin

**Comment by sujit-baniya** [comment]
@hsluoyz Here, https://github.com/casbin/casbin/issues/782

**Comment by sujit-baniya** [comment]
Also can you please suggest which storage would be best for high performance: CSV vs POstgres

**Comment by hsluoyz** [comment]
@sujit-baniya DB adapter is better for production use.

Closed here.
