### ISSUE TITLE
CasbinRule structure with ID, can it be without ID?

### ISSUE THREAD

**Issue by zeroonestring** [casbin/gorm-adapter#109]
CasbinRule structure with ID, can it be without ID?
With ID, the ID reaches the upper limit, which is not good.
How to handle it generally?

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@zeroonestring Hi, thanks for your proposal. But I wonder what is the upper limit, could you explain it?

**Comment by zeroonestring** [comment]
I use Postgresql.
Postgresql bigserial type, the maximum is 9223372036854775807,This is certainly not the optimal solution, after all, it is still time to run out.
Postgresql does not have this restriction if there is no self-incrementing ID.

**Comment by closetool** [comment]
@hsluoyz @zeroonestring Perhaps we could replace the `ID` with hash of other columns.

**Comment by zeroonestring** [comment]
Is ID used for indexing and performance optimization?

**Comment by closetool** [comment]
@zeroonestring It used by ordering https://github.com/casbin/gorm-adapter/blob/b448b9d5871c5c7f2b34cf7868da5e52d72e4e5a/adapter.go#L369.
Are you facing the limitation of policy count? I guess `9223372036854775807` is enough for most projects, it doesn't need to be deleted.

**Comment by zeroonestring** [comment]
If there is no other way, so be it for now.

**Comment by closetool** [comment]
@zeroonestring You could make a issue if you encountered that scenario

**Comment by hsluoyz** [comment]
Closed for now.
