### ISSUE TITLE
The test is error,i use the example.

### ISSUE THREAD

**Issue by deatil** [casbin/gorm-adapter#112]
https://github.com/casbin/gorm-adapter/blob/9500f7f62d505c488deb4b98817fe07728e4b459/adapter_test.go#L157

测试的模型表不该用和适配器相同的表名，一样的表名没法测试的出来换了表名后能不能正常的工作。

我测试了下，换成了其他的表名后，用的还是默认的表名来进行的，那就是说，这个方法目前是有问题的。

The tablename need use other name to test and use same tablename is not good test.

**Comment by deatil** [comment]
目前的gorm设置了默认的表名前缀，但是在这个适配器里没有用上默认的表名前缀。

Set default table prefix,but the adapter do not use it.

**Comment by hsluoyz** [comment]
@closetool @tangyang9464  plz fix this.

**Comment by closetool** [comment]
@deatil Thanks for your help, plz tell me what version are you using and which test has this error.

**Comment by tangyang9464** [comment]
I just noticed that it is right to modify `defaultTableName`（line 258） to the custom table name（such as 'test_casbin_rule'）
https://github.com/casbin/gorm-adapter/blob/9500f7f62d505c488deb4b98817fe07728e4b459/adapter.go#L250-L259
It seems to have created a custom table, but did not modify the tableName in adapter

**Comment by hsluoyz** [comment]
@tangyang9464 plz make a PR

**Comment by tangyang9464** [comment]
@hsluoyz After my test, ```NewAdapterByDBWithCustomTable``` method worked. It creates a new table structure according to custom table, but the table name is still use the defaultTableName.So do we need to modify the table name? such as ‘TestCasbinRule’ struct corresponds to ‘test_casbin_rule’ table name?
