### ISSUE TITLE
mysql: docker run exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by dreamlu** [casbin/gorm-adapter#115]
go: 1.16
github.com/casbin/gorm-adapter/v3 v3.3.1

`GOOS=linux GOARCH=amd64 go build -ldflags '-w -s' -tags netgo -o main`

dockerfile:
```
FROM alpine
WORKDIR /
//....
#EXPOSE 8006
CMD ["./main"]
```

In my web project, Every time, I add `github.com/casbin/gorm-adapter/v3 v3.3.1`  to go.mod and use it, 
eg: `adapter, err := gormadapter.NewAdapter("mysql", ds, conf.GetString("app.db.name"))`
docker run it will be error: `standard_init_linux.go:228: exec user process caused: no such file or directory`. otherwise, other version also has this error

when I use:
dockerfile:
```
FROM ubuntu:20.04
WORKDIR /
//....
#EXPOSE 8006
CMD ["./main"]
```
docker build and run , it will success
or
when I remove `github.com/casbin/gorm-adapter/v3 v3.3.1`,  it will success

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by closetool** [comment]
@dreamlu Could you offer me more infomations, like logs in docker or the whole project on github.

**Comment by dreamlu** [comment]
@closetool 

test branch: https://github.com/dreamlu/gt-crud/tree/csabin

steps: 
1.every time  docker build: project path: `./docker.sh`
2.cd docker,`docker-compose up -d --build`
3.`docker logs d-demo` output `standard_init_linux.go:228: exec user process caused: no such file or directory`

my way: 
remove the `github.com/casbin/gorm-adapter/v3`
or
1.change project Dockerfile: `FROM ubuntu:20.04`
2.Perform the above steps again, there is no above error,follow image was right
![image](https://user-images.githubusercontent.com/21306894/123745142-6abe5880-d8e2-11eb-97fc-04d0df5834b5.png)

**Comment by closetool** [comment]
@dreamlu I could not reproduce this bug.

```
➜  docker git:(master) ✗ docker-compose up -d    
Creating network "docker_demo" with driver "bridge"
Creating d-redis ... done
Creating d-mysql ... done
Creating d-demo  ... done
➜  docker git:(master) ✗ docker logs d-demo
...
2021/06/29 15:41:50 Now You Are Using Gorm-Adapter 3.3.1!
```

main.go
```go
func main() {
	log.Println("Now You Are Using Gorm-Adapter 3.3.1!")
	gin.SetMode(gin.ReleaseMode)
	if conf.GetString("app.devMode") == cons.Dev {
		gin.SetMode(gin.DebugMode)
	}
...
```
dockerfile
```
FROM registry.cn-hangzhou.aliyuncs.com/dreamlu/alpine
MAINTAINER dreamlu <862362681@qq.com>
```
go.mod
```
module demo

go 1.14

require (
	github.com/afocus/captcha v0.0.0-20191010092841-4bd1f21c8868
	github.com/casbin/casbin/v2 v2.31.2
	github.com/casbin/gorm-adapter/v3 v3.3.1
	github.com/dreamlu/gt v1.30.2
	github.com/gin-gonic/gin v1.7.2
	github.com/golang/freetype v0.0.0-20170609003504-e2365dfdc4a0 // indirect
	github.com/medivhzhan/weapp v1.5.1
	github.com/robfig/cron/v3 v3.0.1
	github.com/skip2/go-qrcode v0.0.0-20191027152451-9434209cb086
	golang.org/x/image v0.0.0-20210220032944-ac19c3e999fb // indirect
)

```

**Comment by dreamlu** [comment]
My system is ubuntu 20.04
I test restart my system and in my aliyun cloud ubuntu 18.04 test it, also had this error

**Comment by closetool** [comment]
@dreamlu Any idea about which file could not be found?

**Comment by dreamlu** [comment]
the test branch must exec main-->init() and routers/authz.go,can not annotate those code, it will be error
 I try to annotate those code,it will be right

**Comment by closetool** [comment]
@dreamlu Could you modify your code so I cant reproduce the error easily?

**Comment by dreamlu** [comment]
Could you use teamviewer controller my computer ? my id is 223 381 243 passwod is iy4a9ze9

**Comment by dreamlu** [comment]
I guess not the adapter, mybe the depencies, like `github.com/jackc/pgconn`
,it depency more like this
![image](https://user-images.githubusercontent.com/21306894/123763789-baa71a80-d8f6-11eb-9903-3fff6a5a6173.png)

**Comment by dreamlu** [comment]
I test it，use github.com/dreamlu/gorm-adapter/v3 v3.3.3 replace can resolve;

when I delete about postgres and sqlserver, only use mysql, it was success!

**Comment by closetool** [comment]
After much trying, I found out there's a bug in `github.com/jackc/pgconn`, will tansfer this issue to `pgconn`

**Comment by hsluoyz** [comment]
@closetool they are not replying to this issue: https://github.com/jackc/pgconn/issues/78 , can we remove the pgconn dependency at our side?

**Comment by closetool** [comment]
@hsluoyz Maybe replace this repo by [lib/pg](https://github.com/lib/pq)

**Comment by closetool** [comment]
@hsluoyz Maybe we could.

**Comment by hsluoyz** [comment]
@closetool plz do this!
