### ISSUE TITLE
DeleteRolesForUser not work

### ISSUE THREAD

**Issue by pandaria2012** [casbin/gorm-adapter#117]
code:

```go
func (p *CasbinCtrl) AddRolesForUser(c *gin.Context) {
	e := casbin.GetEnforcer()

	ok, err := e.DeleteRolesForUser("admin")

	if ok == false && err != nil {
		util.RespFailed(c, util.ErrorOperationAddFailure, err.Error())
		return
	}

	//_ = e.SavePolicy()

	ok, _ = e.AddRolesForUser("admin", []string{"role1", "role2", "role3"})
	if ok == false {
		fmt.Println("+++++++")
		util.RespFailed(c, util.ErrorOperationAddFailure, ok)
		return
	}

	util.RespSuccess(c, ok)
}
```

log:

```log
2021/07/09 14:49:47 C:/Users/91149/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.3.1/adapter.go:644
[4.486ms] [rows:0] 

2021/07/09 14:49:47 C:/Users/91149/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.3.1/adapter.go:567 Error 1062: Duplicate entry 'g-admin-role1----' for key 'casbin_rule.idx_casbin_rule'
[1.500ms] [rows:0] INSERT INTO `casbin_rule` (`ptype`,`v0`,`v1`,`v2`,`v3`,`v4`,`v5`) VALUES ('g','admin','role1','','','','')
+++++++
[GIN] 2021/07/09 - 14:49:47 | 200 |     12.9985ms |       127.0.0.1 | GET      "/api/v1/access/user/role/add/1"`
```

and i found adapter.go:644

```go
err := db.Delete(a.getTableInstance(), args...).Error
```

it seems not excuted.

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@pandaria2012 May I have your model and policy file?

**Comment by pandaria2012** [comment]
CREATE TABLE `tb_casbin_rule`  (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `ptype` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v0` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v1` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v2` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v3` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v4` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `v5` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `unique_index`(`ptype`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tb_casbin_rule
-- ----------------------------
INSERT INTO `tb_casbin_rule` VALUES (18, 'g', 'admin', 'role1', '', '', '', '');
INSERT INTO `tb_casbin_rule` VALUES (19, 'g', 'admin', 'role2', '', '', '', '');
INSERT INTO `tb_casbin_rule` VALUES (20, 'g', 'admin', 'role3', '', '', '', '');

SET FOREIGN_KEY_CHECKS = 1;






[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act







gorm.io/gorm v1.21.11



i found that it seems the gorm problem

`	err := db.Delete(a.getTableInstance(), args...).Error`

no sql print in console.

**Comment by closetool** [comment]
@pandaria2012 Which version gorm are you using?

**Comment by pandaria2012** [comment]
> @pandaria2012 Which version gorm-adapter are you using?

github.com/casbin/gorm-adapter/v3 v3.3.1
github.com/casbin/casbin/v2 v2.31.9
gorm.io/gorm v1.21.11

go 1.16

**Comment by closetool** [comment]
@pandaria2012 I write a demo, and it works well. If it's because there no data in your db, or something else.

code
```go
func main() {
    e, err := casbin.NewEnforcer("./examples/rbac_model.conf","./examples/rbac_policy.csv")
    if err != nil {
        panic(err)
    }

    fmt.Println(e.Enforce("bob","data2","read"))

    fmt.Println(e.DeleteRolesForUser("bob"))

    fmt.Println(e.Enforce("bob","data2","read"))
}
```

result
```
➜  playground go run ./main.go 
true <nil>
true <nil>
false <nil>
```

**Comment by hsluoyz** [comment]
@closetool can you put your demo to a github repo?

**Comment by closetool** [comment]
@hsluoyz @pandaria2012 demo refer to https://github.com/closetool/playground

**Comment by pandaria2012** [comment]
> @hsluoyz @pandaria2012 refer to https://github.com/closetool/playground

using the gorm-adapter, not the file-adapter

e.DeleteRolesForUser("bob")    // this does well in casbin, but not auto save(delete) in the database;

because this gorm:
err := db.Delete(a.getTableInstance(), args...).Error
the Delete method says([https://gorm.io/docs/delete.html#Batch-Delete](https://gorm.io/docs/delete.html#Batch-Delete)):
`
The specified value has no primary value, GORM will perform a batch delete, it will delete all matched records
`
i debuged at this [line](https://github.com/casbin/gorm-adapter/blob/b1c668977bfb4c6e5586a011f915c9ba4d8d2bfa/adapter.go#L643)
that i found there is no **where condition**, just the Initialized TableInstance(CasbinRule)

**Comment by closetool** [comment]
@pandaria2012 I wrote a unit test for it. https://github.com/closetool/gorm-adapter/blob/8b3bf70a2575dd9f4dce208445dea71723b8137f/adapter_test.go#L297

**Comment by closetool** [comment]
@pandaria2012 I wrote a test for it. https://github.com/closetool/gorm-adapter/blob/8a1073e622ed428f08f83aa174a4678400165a31/adapter_test.go#L297

**Comment by pandaria2012** [comment]
> @pandaria2012 I wrote a test for it. https://github.com/closetool/gorm-adapter/blob/8a1073e622ed428f08f83aa174a4678400165a31/adapter_test.go#L297
> I trust there's a bug, but I could not find it out.

e, _ := casbin.NewEnforcer("examples/rbac_with_domains_model.conf", "examples/rbac_with_domains_policy.csv")

the second param `"examples/rbac_with_domains_policy.csv"` is the file-adapter

change it like that:
`
a, _ := gormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/") 
e, _ := casbin.NewEnforcer("examples/rbac_with_domains_model.conf", a)
`

use gormadapter;
[gormadapter aotusave is checked](https://casbin.org/docs/en/adapters)

you will find what i say.
the gormadapter will not autosave when DeleteRolesForUser in database, but it dose in casbin(process memory).

**Comment by closetool** [comment]
@pandaria2012 No, I used gorm-adapter
refer to https://github.com/closetool/gorm-adapter/blob/8a1073e622ed428f08f83aa174a4678400165a31/adapter_test.go#L300

**Comment by pandaria2012** [comment]
> @pandaria2012 No, I used gorm-adapter
> refer to https://github.com/closetool/gorm-adapter/blob/8a1073e622ed428f08f83aa174a4678400165a31/adapter_test.go#L300

Yes, casbin does well.

but after delete, you can login to mysql server, select from the table, the record is still there.


trying do this:

1. add roles to user
2. delete role from user
3. add another roles to(that contains step one's role) user
ex:
ok, _ = e.AddRolesForUser("admin", []string{"role1", "role2"})
ok, err := e.DeleteRolesForUser("admin")
ok, _ = e.AddRolesForUser("admin", []string{"role1", "role2", "role3"})
you will get sql error

**Comment by closetool** [comment]
@pandaria2012 I checked the database, the record has been deleted. And I wrote a test for it.
https://github.com/closetool/gorm-adapter/blob/3168472714398e7006ec0088af7be46084bb0773/adapter_test.go#L297
And it seems still fine. How about you write some test for it?

**Comment by pandaria2012** [comment]
> @pandaria2012 I checked the database, the record has been deleted. And I wrote a test for it.
> https://github.com/closetool/gorm-adapter/blob/6fa5fd82f5318a0fbc0654628d199c9925ac3257/adapter_test.go#L297
> And it seems still fine. How about you write some tests for it?

Hi, sorry to reply so late, I'm a little busy recently.
as you said, i fork the code, and make some tests, all things are well.
and i use another cumputer to run my code, there are doing well too.

maybe it's my golang enviroment problems, i guess.

anyway, i'll close this issue, and thanks for your replay.
