### ISSUE TITLE
[QUESTION] How to drop the entire casbin rule table

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#119]
We are using casbin in conjunction with gorm adapter in a cloud based multi tenant system.
So when a new tenant gets onboarded we create a table of the format casbin_rule_<tenantMoniker>

Now when the tenant gets off boarded we want to drop the entire casbin_rule_<tenantMoniker> table
Which API can we use for this

**Comment by hsluoyz** [comment]
@arafat-java the adapter usually doesn't drop table, it only creates table if necessary. So I think you have to drop the table by yourself.
