### ISSUE TITLE
[BUG] e.GetNamedPolicy("p") gives incorrect response if data contains comma ( , ) character

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#123]
We are using casbin with gorm-adapter.

My model.conf is as follows
```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

```

My data in casbin_rule looks as follows

```
id    | ptype | v0                | v1         | v2    | v3   | v4 | v5
------+-------+-------------------+------------+-------+------+----+---
43614 | p     | abcxyz            | MyObjectId | write | task |    |   
43615 | p     | abc,xyz           | MyObjectId | write | task |    |   

```

Now when I call GetNamedPolicy on the enforcer as follows
`e.GetNamedPolicy("p")`

For 1st row it returns array data correctly as follows

```
0 =  "abcxyz"
1 =  "MyObjectId"
2 =  "write"
3 =  "task"

```

**However for the 2nd Row it gives incorrect data as follows**
```
0 =  "abc"
1 =  "xyz"
2 =  "MyObjectId"
3 =  "write"
4 =  "task"

```

Note that it gives 1st element of array as "abc" , 2nd element as "xyz" and subsequently all the elements are pushed 1 place down and overall it returns 1 extra element

**Comment by hsluoyz** [comment]
@closetool @tangyang9464

**Comment by tangyang9464** [comment]
@arafat-java
Obviously, the ``,`` is a separator, why not replace it, such as ``abc_xyz `` or other separator?

**Comment by hsluoyz** [comment]
@tangyang9464 this is a DB adapter and I don't think we need to use comma as separator, right? Even for the built-in CSV adapter, CSV has a way to escape the comma by quoting the string. So this is something we need to fix.

**Comment by tangyang9464** [comment]
> @tangyang9464 this is a DB adapter and I don't think we need to use comma as separator, right? Even for the built-in CSV adapter, CSV has a way to escape the comma by quoting the string. So this is something we need to fix.

ok, I will think about it again
