### ISSUE TITLE
The rules are not added as a single SQL INSERT when using e.AddPolicies(rules) nor is there transaction maintained

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#129]
With gorm adapter when we use `e.AddPolicies(rules)` the statement within rules are not inserted as part of a single SQL INSERT statement. Rather individual inserts are fired.

Example : If following 3 elements are passed in rules
```
 0 = {string} "tenantCUST-DemoGroup01"
 1 = {string} "11223"
 2 = {string} "write"
 3 = {string} "task"

 0 = {string} "Jill.warner@gmail.com"
 1 = {string} "11223"
 2 = {string} "read"
 3 = {string} "task"

 0 = {string} "Perf@mail.com"
 1 = {string} "11223"
 2 = {string} "write"
 3 = {string} "task"
 ```

Then the adapter makes 3 individual INSERT statements as follows
```
INSERT INTO "casbin_rule_perfdecoup" ("ptype","v0","v1","v2","v3","v4","v5") VALUES ('p','tenantCUST-DemoGroup01','11223','write','task','','') RETURNING "id"
INSERT INTO "casbin_rule_perfdecoup" ("ptype","v0","v1","v2","v3","v4","v5") VALUES ('p','Jill.warner@gmail.com','11223','read','task','','') RETURNING "id"
INSERT INTO "casbin_rule_perfdecoup" ("ptype","v0","v1","v2","v3","v4","v5") VALUES ('p','Perf@mail.com','11223','write','task','','') RETURNING "id"

```

And the worst part is that it does not make that as part of a transaction.
So that way sometimes it ends up inserting partial data

So either it should enclose that individual INSERT statements within a transaction or maybe insert with a single insert like follows
```
INSERT INTO "casbin_rule_perfdecoup" ("ptype","v0","v1","v2","v3","v4","v5") 
VALUES 
('p','tenantCUST-DemoGroup01','11223','write','task','',''), 
('p','Jill.warner@gmail.com','11223','read','task','',''), 
('p','Perf@mail.com','11223','write','task','','')
```

That way either all records get inserted or none get inserted and the data is consistent

**Comment by hsluoyz** [comment]
@MRGUOKING plz fix the wrong label:

![AUL5)O%X9A)``M9Z{CQ0HYJ](https://user-images.githubusercontent.com/3787410/132610235-d4aac955-1dca-40b4-a423-68a133f68511.png)

**Comment by hsluoyz** [comment]
@tangyang9464 plz change to batch insert.

**Comment by arafat-java** [comment]
@hsluoyz Removed the [BUG] label

**Comment by tangyang9464** [comment]
@arafat-java https://github.com/casbin/gorm-adapter/blob/ed2cfa40c4091064e8cd06d44730f641baec76b7/adapter.go#L564-L570
This method uses a transaction (``a.db.Transaction``), and it will roll back when the ``Create`` fails and returns an error. Does this not work for you?

**Comment by hsluoyz** [comment]
@tangyang9464 but we better do it in a batch to improve performance. Also change RemoveXxx() and UpdateXxx().

**Comment by arafat-java** [comment]
> 
> 
> @arafat-java
> 
> https://github.com/casbin/gorm-adapter/blob/ed2cfa40c4091064e8cd06d44730f641baec76b7/adapter.go#L564-L570
> 
> This method uses a transaction (`a.db.Transaction`), and it will roll back when the `Create` fails and returns an error. Does this not work for you?

It does @tangyang9464 . Actually it was printing the insert statements and that caused me to think that it was actually going ahead and inserting those records. Now when I dig further I realized that it was simply printing the statements and not inserting records if even one record has the duplicate error. Sorry for the confusion. So I am good with that, but as @hsluoyz  pointed out it will be good from performance point of view if we do the batch update

**Comment by tangyang9464** [comment]
> @tangyang9464 but we better do it in a batch to improve performance. Also change RemoveXxx() and UpdateXxx().

@hsluoyz I think batch insert is ok but batch remove and update are not suitable for our needs. SQL has no batch for remove or update and can only be executed individually
