### ISSUE TITLE
Can't pull gorm-adapter

### ISSUE THREAD

**Issue by alasad311** [casbin/gorm-adapter#141]
Ive been trying to pull using

`go get github.com/casbin/gorm-adapter/v3`

Im getting the below error

`gorm.io/driver/sqlserver
..\..\..\go\pkg\mod\gorm.io\driver\sqlserver@v1.0.9\update.go:13:18: cannot use db (type *gorm.DB) as type *callbacks.Config in argument to callbacks.Update`
`gorm.io/driver/postgres
..\..\..\go\pkg\mod\gorm.io\driver\postgres@v1.1.2\postgres.go:46:3: unknown field 'WithReturning' in struct literal of type callbacks.Config`

### Ive tried below;

`go clean -modcache`
 
Just in case but luck keep on getting the same above error.

`go: downloading github.com/casbin/gorm-adapter/v3 v3.4.5
go: downloading github.com/casbin/gorm-adapter v1.0.0
go: downloading github.com/casbin/casbin/v2 v2.39.0
go: downloading gorm.io/driver/mysql v1.1.3
go: downloading gorm.io/driver/postgres v1.1.2
go: downloading gorm.io/driver/sqlserver v1.0.9
go: downloading gorm.io/gorm v1.22.3
go: downloading gorm.io/plugin/dbresolver v1.1.0
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/jackc/pgx/v4 v4.13.0
go: downloading github.com/denisenkom/go-mssqldb v0.11.0
go: downloading github.com/Knetic/govaluate v3.0.1-0.20171022003610-9aa49832a739+incompatible
go: downloading github.com/jinzhu/inflection v1.0.0
go: downloading github.com/jinzhu/now v1.1.2
go: downloading github.com/jackc/pgconn v1.10.0
go: downloading github.com/jackc/pgtype v1.8.1
go: downloading github.com/jackc/pgio v1.0.0
go: downloading github.com/jackc/pgproto3/v2 v2.1.1
go: downloading github.com/jackc/chunkreader/v2 v2.0.1
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
go: downloading golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe
# gorm.io/driver/sqlserver
..\..\..\go\pkg\mod\gorm.io\driver\sqlserver@v1.0.9\update.go:13:18: cannot use db (type *gorm.DB) as type *callbacks.Config in argument to callbacks.Update
# gorm.io/driver/postgres
..\..\..\go\pkg\mod\gorm.io\driver\postgres@v1.1.2\postgres.go:46:3: unknown field 'WithReturning' in struct literal of type callbacks.Config`

Code im trying to run for testing

> package route

> 
> import (
> 	"fmt"
> 
> 	"github.com/casbin/casbin/v2"
> 	gormadapter "github.com/casbin/gorm-adapter/v3"
> 	"github.com/gin-gonic/gin"
> 	"gorm.io/gorm"
> )
> 
> //SetupRoutes : all the routes are defined here
> func SetupRoutes(db *gorm.DB) {
> 	httpRouter := gin.Default()
> 	// Initialize  casbin adapter
> 	adapter, err := gormadapter.NewAdapterByDB(db)
> 	if err != nil {
> 		panic(fmt.Sprintf("failed to initialize casbin adapter: %v", err))
> 	}
> 
> 	// // Load model configuration file and policy store adapter
> 	enforcer, err := casbin.NewEnforcer("config/policy_model.conf", adapter)
> 	if err != nil {
> 		panic(fmt.Sprintf("failed to create casbin enforcer: %v", err))
> 	}
> 
> 
> 	httpRouter.Run()
> 
> }

**Comment by hsluoyz** [comment]
@abichinger

**Comment by abichinger** [comment]
@alasad311 have you tried to update the modules? similar issue: https://github.com/go-gorm/gorm/issues/4822
```
go get -u gorm.io/gorm
go get -u gorm.io/driver/sqlserver
go get -u gorm.io/driver/postgres
```

**Comment by alasad311** [comment]
Yes i did, even tried to change versions manually though go.mod the same issue persists

**Comment by hsluoyz** [comment]
@abichinger can you reproduce it in your machine?

@alasad311 can you reproduce it in another machine?

**Comment by abichinger** [comment]
Yes, I was able to reproduce it on my machine.

Steps:
1. execute:
```
mkdir gorm-adapter-test
cd gorm-adapter-test
go mod init example.com/m
```
2. create file main.go:
```go
package main

import (
	"fmt"

	gormadapter "github.com/casbin/gorm-adapter/v3"
	"gorm.io/gorm"
)

func initAdapter(db *gorm.DB) *gormadapter.Adapter {
	// Initialize casbin adapter
	adapter, err := gormadapter.NewAdapterByDB(db)
	if err != nil {
		panic(fmt.Sprintf("failed to initialize casbin adapter: %v", err))
	}

	return adapter
}

func main() {

}
```

3. execute:
```
go mod tidy
go build
```

Output of `go build`:
```
# gorm.io/driver/sqlserver
../../../go/pkg/mod/gorm.io/driver/sqlserver@v1.0.9/update.go:13:18: cannot use db (type *gorm.DB) as type *callbacks.Config in argument to callbacks.Update
# gorm.io/driver/postgres
../../../go/pkg/mod/gorm.io/driver/postgres@v1.1.2/postgres.go:46:3: unknown field 'WithReturning' in struct literal of type callbacks.Config
```

`go.mod`:
```go
module example.com/m

go 1.17

require (
	github.com/casbin/gorm-adapter/v3 v3.4.5
	gorm.io/gorm v1.22.3
)

require (
	github.com/Knetic/govaluate v3.0.1-0.20171022003610-9aa49832a739+incompatible // indirect
	github.com/casbin/casbin/v2 v2.37.4 // indirect
	github.com/denisenkom/go-mssqldb v0.11.0 // indirect
	github.com/go-sql-driver/mysql v1.6.0 // indirect
	github.com/golang-sql/civil v0.0.0-20190719163853-cb61b32ac6fe // indirect
	github.com/jackc/chunkreader/v2 v2.0.1 // indirect
	github.com/jackc/pgconn v1.10.0 // indirect
	github.com/jackc/pgio v1.0.0 // indirect
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgproto3/v2 v2.1.1 // indirect
	github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b // indirect
	github.com/jackc/pgtype v1.8.1 // indirect
	github.com/jackc/pgx/v4 v4.13.0 // indirect
	github.com/jinzhu/inflection v1.0.0 // indirect
	github.com/jinzhu/now v1.1.2 // indirect
	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
	golang.org/x/text v0.3.7 // indirect
	gorm.io/driver/mysql v1.1.2 // indirect
	gorm.io/driver/postgres v1.1.2 // indirect
	gorm.io/driver/sqlserver v1.0.9 // indirect
	gorm.io/plugin/dbresolver v1.1.0 // indirect
)
```

Updating the modules resolves the build error for me:
```
$ go get -u gorm.io/gorm
go get -u gorm.io/driver/sqlserver
go get -u gorm.io/driver/postgres
go get: upgraded golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 => v0.0.0-20211108221036-ceb1ce70b4fa
go get: upgraded gorm.io/driver/sqlserver v1.0.9 => v1.2.1
go get: upgraded gorm.io/driver/postgres v1.1.2 => v1.2.2
$ go build
$ 
```

**Comment by hsluoyz** [comment]
@abichinger why this happens? Is it because the user has once used an old version of Casbin or gorm-adapter or gorm before? Will this error happen for a first-time user (just get Go installed, doesn't run anything yet) ?

**Comment by abichinger** [comment]
@hsluoyz I think this affects all users, which use `gorm.io/gorm` and `github.com/casbin/gorm-adapter/v3` inside their project.

The problem is that go will download the latest version of `gorm` and the `gorm-adapter` requires old drivers, which are not compatible with the latest version of `gorm`.

**Comment by hsluoyz** [comment]
@abichinger  We (gorm-adapter) can updates to use latest gorm version. We just need to upgrade our dependencies. Does this help?

**Comment by abichinger** [comment]
@hsluoyz Yes, that would help.
But as I mentioned [here](https://github.com/casbin/gorm-adapter/issues/142#issuecomment-971368123), it would not prevent this issue from happening again in the future.

**Comment by hsluoyz** [comment]
@abichinger deleting those functions will result in breaking change. I think for now a temp fix is already enough.

**Comment by admi2u** [comment]
i have the save problem, how to fix it now?

**Comment by hsluoyz** [comment]
@Abingcbc plz follow up this issue
