### ISSUE TITLE
gormv2 and casbin

### ISSUE THREAD

**Issue by odeCe** [casbin/gorm-adapter#142]
```go
    package main
    import (
	    "github.com/casbin/casbin/v2"
	    gormadapter "github.com/casbin/gorm-adapter/v3"
	    "gorm.io/driver/mysql"
	    "gorm.io/gorm"
    )
    
    func main() {
	    // Increase the column size to 512.
	    type CasbinRule struct {
		    ID    uint   `gorm:"primaryKey;autoIncrement"`
		    Ptype string `gorm:"size:512;uniqueIndex:unique_index"`
		    V0    string `gorm:"size:512;uniqueIndex:unique_index"`
		    V1    string `gorm:"size:512;uniqueIndex:unique_index"`
		    V2    string `gorm:"size:512;uniqueIndex:unique_index"`
		    V3    string `gorm:"size:512;uniqueIndex:unique_index"`
		    V4    string `gorm:"size:512;uniqueIndex:unique_index"`
		    V5    string `gorm:"size:512;uniqueIndex:unique_index"`
	    }
	    dsn:="root:123123@tcp(localhost:3307)/test?charset=utf8mb4&parseTime=True&loc=Local"
	    db, _ := gorm.Open(mysql.Open(dsn),&gorm.Config{})
    
	    // Initialize a Gorm adapter and use it in a Casbin enforcer:
	    // The adapter will use an existing gorm.DB instnace.
	    a, _ := gormadapter.NewAdapterByDBWithCustomTable(db, &CasbinRule{})
	    e, _ := casbin.NewEnforcer("examples/rbac_model.conf", a)
    
	    // Load the policy from DB.
	    e.LoadPolicy()
    
	    // Check the permission.
	    e.Enforce("alice", "data1", "read")
    
	    // Modify the policy.
	    // e.AddPolicy(...)
	    // e.RemovePolicy(...)
    
	    // Save the policy back to DB.
	    e.SavePolicy()
    }
```

go run main.go

![image](https://user-images.githubusercontent.com/73453065/141983118-4d2e082f-db44-4ba3-b7e1-8c7f624867fa.png)

    # gorm.io/driver/sqlserver
    E:\Code\Go\pkg\mod\gorm.io\driver\sqlserver@v1.0.9\update.go:13:18: cannot use db (type *gorm.DB) as type *callbacks.Config in argument to callbacks.Update
    # gorm.io/driver/postgres
    E:\Code\Go\pkg\mod\gorm.io\driver\postgres@v1.1.2\postgres.go:46:3: unknown field 'WithReturning' in struct literal of type callbacks.Config

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc

**Comment by abichinger** [comment]
same error as #141

**Comment by hsluoyz** [comment]
@abichinger how to fix it then?

**Comment by abichinger** [comment]
@hsluoyz  I'm not sure how to fix it.
A quick fix for me was to [update the modules](https://github.com/casbin/gorm-adapter/issues/141#issuecomment-968369260).

Maybe the requirements of gorm-drivers should be removed from the gorm-adapter.
Then the gorm-adapter can only be initialized by passing an instance of `gorm.DB`.
In other words, I would delete the following functions:
```go
func NewAdapter(driverName string, dataSourceName string, params ...interface{}) (*Adapter, error)
func openDBConnection(driverName, dataSourceName string) (*gorm.DB, error)
```

**Comment by odeCe** [comment]
I also want to replace, but the project already uses gorm v2

Is there any way to use gorm v2

**Comment by MELF2018** [comment]
You need to modify the go.mod file for your project
require (
	github.com/casbin/casbin/v2 v2.37.4
	github.com/casbin/gorm-adapter/v3 v3.4.5
	github.com/go-sql-driver/mysql v1.6.0
	gorm.io/driver/mysql v1.1.2
	gorm.io/gorm v1.21.15
)

**Comment by melf-xyzh** [comment]
You need to modify the go.mod file for your project
require (
github.com/casbin/casbin/v2 v2.37.4
github.com/casbin/gorm-adapter/v3 v3.4.5
github.com/go-sql-driver/mysql v1.6.0
gorm.io/driver/mysql v1.1.2
gorm.io/gorm v1.21.15
)

**Comment by Abingcbc** [comment]
Maybe we should update the version of sql-server and Postgres in gorm-adapter?

https://github.com/casbin/gorm-adapter/blob/master/go.mod#L12

**Comment by abichinger** [comment]
@Abingcbc I guess that would solve the error for now. But then the same problem may occur in the future.

I think we should remove the dependencies of gorm drivers.

**Comment by odeCe** [comment]
package main

import (
	"fmt"
	"github.com/casbin/casbin/v2"
	"log"
)
var E *casbin.Enforcer
func main() {

	e,err:= casbin.NewEnforcer("resources/model.conf")
	if err!=nil{
		log.Fatal()
	}
	err=e.LoadPolicy()
	if err!=nil{
		log.Fatal()
	}
	E=e

	initPolicy()

	b,_:=e.Enforce("lisi", "/depts", "POST")
	if b{
		fmt.Println("ok")
	}else{
		fmt.Println("no")
	}
}


//grom loading
func initPolicy()  {
	E.AddRoleForUser("admin","member")
	E.AddRoleForUser("zhang","admin")
	E.AddRoleForUser("lisi","member")

	E.AddPolicy("member","/depts","GET")
	E.AddPolicy("admin","/depts","POST")
}
