### ISSUE TITLE
Adapter UpdatePolicy error:

### ISSUE THREAD

**Issue by GENG824** [casbin/gorm-adapter#144]
when I use e.UpdatePolicy ,error:

panic: interface conversion: *gormadapter.Adapter is not persist.UpdatableAdapter: missing method UpdateFilteredPolicies

**Comment by hsluoyz** [comment]
@abichinger @Abingcbc @seriouszyx

**Comment by Abingcbc** [comment]
@GENG824 Could you provide reproduction progress?

**Comment by hsluoyz** [comment]
@GENG824 it has been added in this PR. Please use the latest version.
