### ISSUE TITLE
Option to turn off auto migration?

### ISSUE THREAD

**Issue by Genora51** [casbin/gorm-adapter#145]
I have a use case where gorm automigration is done at deploy-time in a CI/CD pipeline, rather than at runtime; the database user on the deployed application does not have permissions to create or drop tables.

Is there a way to prevent auto-migration of the database tables when a `NewAdapter` is initialised, and if not, can this be implemented somehow?

**Comment by Genora51** [comment]
Any chance of an update on this?

**Comment by hsluoyz** [comment]
@Genora51 sorry that we missed this issue.

I think @closetool first developed the auto migration part?

Can anyone add an option? @tangyang9464 @Abingcbc @fabian4

**Comment by Goxiaoy** [comment]
Any progress on this feature?

**Comment by hsluoyz** [comment]
@tangyang9464 @seriouszyx

**Comment by Goxiaoy** [comment]
And for `SavePolicy`, it's better to truncate table instead of recreation
https://github.com/casbin/gorm-adapter/blob/7b3bc27c2b301e05607450cdf68aad047507943f/adapter.go#L507-L516

**Comment by Goxiaoy** [comment]
Please reopen this issue @hsluoyz 
`SavePolicy` use DDL statement

> And for `SavePolicy`, it's better to truncate table instead of recreation
> 
> https://github.com/casbin/gorm-adapter/blob/7b3bc27c2b301e05607450cdf68aad047507943f/adapter.go#L507-L516

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
> Please reopen this issue @hsluoyz 
> `SavePolicy` use DDL statement
> 
> > And for `SavePolicy`, it's better to truncate table instead of recreation
> > 
> > https://github.com/casbin/gorm-adapter/blob/7b3bc27c2b301e05607450cdf68aad047507943f/adapter.go#L507-L516
> 
> 

@Goxiaoy Sorry I didn't add this part, I think a new PR should be opened for this part and this issue is irrelevant, so there is no need to reopen it. Can you do this PR？

**Comment by tangyang9464** [comment]
> Please reopen this issue @hsluoyz `SavePolicy` use DDL statement
> 
> > And for `SavePolicy`, it's better to truncate table instead of recreation
> > https://github.com/casbin/gorm-adapter/blob/7b3bc27c2b301e05607450cdf68aad047507943f/adapter.go#L507-L516

@Goxiaoy solved by #163
