### ISSUE TITLE
panic: github.com/casbin/gorm-adapter/v3@v3.4.6/adapter.go:449

### ISSUE THREAD

**Issue by forTWOS** [casbin/gorm-adapter#147]
```
	a, err := gormadapter.NewAdapterByDB(s.dao.DB().MasterDB().DB)
	if err != nil {
		// panic(err)
	}
	ulog.Debug("%#+v,%t", a, a == nil)
	s.CasbinSyncedEnforcer, _ = casbin.NewSyncedEnforcer(cfg.Casbin.ModelPath, a)
```

> goroutine 1 [running]:
> github.com/casbin/gorm-adapter/v3.(*Adapter).IsFiltered(0xc0004ae180)
>         C:/Users/xx/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.4.6/adapter.go:449
> github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc0004ae180, 0x1b, {0x226e9426f38, 0x0})
>         C:/Users/xx/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.4/enforcer.go:176 +0xe6
> github.com/casbin/casbin/v2.(*Enforcer).InitWithAdapter(0xc0004ae180, {0xc00049e160, 0x0}, {0x226e9426f38, 0x0})
>         C:/Users/xx/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.4/enforcer.go:154 +0x5c
> github.com/casbin/casbin/v2.NewEnforcer({0xc0001c9db0, 0x2, 0x1652040})
>         C:/Users/xx/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.4/enforcer.go:103 +0x30c
> github.com/casbin/casbin/v2.NewSyncedEnforcer({0xc0001c9db0, 0x2, 0x2})
>         C:/Users/xx/go/pkg/mod/github.com/casbin/casbin/v2@v2.37.4/enforcer_synced.go:38 +0x4c
> ucenter/app/gm/service/system.New(0x2ab9160)
>         D:/gocode/src/uc-web-offic-gm/app/gm/service/system/service.go:35 +0x171

`	if e.adapter != nil && (!ok || ok && !fa.IsFiltered()) {`
    `e.adapter != nil` result in false

`interface != nil` is not compatible

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by hsluoyz** [comment]
@forTWOS can you share more info about the issue? What's your question?

**Comment by hsluoyz** [comment]
Closed as stale.
