### ISSUE TITLE
Question : How to close connection created using pgAdapter.NewFilteredAdapter

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#148]
Ours is a cloud based multi tenant system and we cache one adapter instance (`pgAdapter.NewFilteredAdapte`r) for each tenant.
However when we remove the adapter instance from the cache the connection to DB is not released
So, how to close connection created using `pgAdapter.NewFilteredAdapter`

**Comment by hsluoyz** [comment]
@tangyang9464 @Abingcbc @fabian4

**Comment by Abingcbc** [comment]
@arafat-java  You can use `finalizer(a *Adapter)`
Refer to https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L81

**Comment by arafat-java** [comment]
> @arafat-java You can use `finalizer(a *Adapter)` Refer to https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L81

How can I call that `finalizer(a *Adapter)`. I have the reference of Adapter that I get via `pgAdapter.NewFilteredAdapter`. 
Is there any code sample

**Comment by Abingcbc** [comment]
> > @arafat-java You can use `finalizer(a *Adapter)` Refer to https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L81
> 
> How can I call that `finalizer(a *Adapter)`. I have the reference of Adapter that I get via `pgAdapter.NewFilteredAdapter`. Is there any code sample

```
adapter := pgAdapter.NewFilteredAdapter()
pgAdapter.finalizer(adapter)
```

**Comment by hsluoyz** [comment]
@Abingcbc isn't `finalizer()` a private method? Can it be called from outside?

**Comment by Abingcbc** [comment]
> @Abingcbc isn't `finalizer()` a private method? Can it be called from outside?

Yes, it's my mistake.

**Comment by Abingcbc** [comment]
@arafat-java  The connection will be closed when the adapter is finalized and released by runtime gc. 
Do you need to manually close the connection immediately? The current version of the adapter doesn't support but we can add this feature.

**Comment by hsluoyz** [comment]
@Abingcbc plz add this feature

**Comment by arafat-java** [comment]
Thanks guys for the quick resolution
