### ISSUE TITLE
Native Go SQLite implementation

### ISSUE THREAD

**Issue by TJM** [casbin/gorm-adapter#150]
I propose that sqlite should be supported, perhaps using this implementation: `"github.com/glebarez/sqlite"`

REF: https://gorm.io/docs/connecting_to_the_database.html#SQLite

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by hsluoyz** [comment]
@TJM can you make a PR to support it?

**Comment by TJM** [comment]
@hsluoyz I tried, but failed. :(  I use sqlite for local development. I have tried with both the 'c' implementation and this golang implementation. They both work fine for my application, which uses gorm, but I get an error about "id" fields when I try to use it for casbin. The funny part is that it works fine the *first* time you start, but the second time you start the app (where the database has already been populated) and it tries to create the enforcer, this error comes up:

```
.../vendor/github.com/casbin/gorm-adapter/v3/adapter.go:373 SQL logic error: duplicate column name: id (1)
[0.017ms] [rows:0] ALTER TABLE `casbin_rule` ADD `id` integer

.../middleware.createEnforcer() failed to initialize casbin gorm adapter: SQL logic error: duplicate column name: id (1) 
exit status 1
```

SO, it doesn't do any good to add it to the (internal?) supported databases. There is apparently some other problem relating to "id" column. Honestly, I don't think that this code should have any direct support for databases. It should just take the gorm.DB and use whatever gorm supports. :)

... that way I could reduce the amount of imported code for the other N databases that I have no intention of using :)

~tommy

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@TJM I found the bug was because of this line of code. 
https://github.com/casbin/gorm-adapter/blob/34e13d4d2dd3d88170d9e5a38c5f671e11328fb8/adapter.go#L377
See [AutoMigrate bug](https://github.com/go-gorm/sqlite/issues/7). Since [glebarez/sqlite](https://github.com/glebarez/sqlite) is too backward and has not been updated, this PR cannot be implemented at present.

Regarding your second question, I don't quite understand what it means. If you have a better idea, you can open a new PR

**Comment by glebarez** [comment]
> @TJM I found the bug was because of this line of code.
> 
> https://github.com/casbin/gorm-adapter/blob/34e13d4d2dd3d88170d9e5a38c5f671e11328fb8/adapter.go#L377
> 
> 
> See [AutoMigrate bug](https://github.com/go-gorm/sqlite/issues/7). Since [glebarez/sqlite](https://github.com/glebarez/sqlite) is too backward and has not been updated, this PR cannot be implemented at present.
> Regarding your second question, I don't quite understand what it means. If you have a better idea, you can open a new PR

Actually it is not falling backwards.
Here's the diff between fork and the original repo https://github.com/glebarez/sqlite/compare/master...go-gorm:master
The only thing is deps, which are already up to date in fork.

**Comment by glebarez** [comment]
@TJM does your case fail with both CGo and pure-Go implementations? Or is it just Pure-Go fails ?

**Comment by tangyang9464** [comment]
> > @TJM I found the bug was because of this line of code.
> > https://github.com/casbin/gorm-adapter/blob/34e13d4d2dd3d88170d9e5a38c5f671e11328fb8/adapter.go#L377
> > 
> > See [AutoMigrate bug](https://github.com/go-gorm/sqlite/issues/7). Since [glebarez/sqlite](https://github.com/glebarez/sqlite) is too backward and has not been updated, this PR cannot be implemented at present.
> > Regarding your second question, I don't quite understand what it means. If you have a better idea, you can open a new PR
> 
> Actually it is not falling backwards. Here's the diff between fork and the original repo [glebarez/sqlite@master...go-gorm:master](https://github.com/glebarez/sqlite/compare/master...go-gorm:master) The only thing is deps, which are already up to date in fork.

@glebarez Yes, you are right, I neglected. If so, when this bug is resolved I'd be gald to implement our functionality based on it.

**Comment by tangyang9464** [comment]
> @TJM does your case fail with both CGo and pure-Go implementations? Or is it just Pure-Go fails ?

@glebarez I tested it. Fail with both CGo and pure-Go implementations.

**Comment by glebarez** [comment]
> > @TJM does your case fail with both CGo and pure-Go implementations? Or is it just Pure-Go fails ?
> 
> @glebarez I tested it. Fail with both CGo and pure-Go implementations.

created an issue https://github.com/go-gorm/gorm/issues/5282 to the upstream.

**Comment by TJM** [comment]
You guys rock! Thanks! 

I am passing it a glebarez/sqlite `*gorm.DB`, and it is working great!

**Comment by tangyang9464** [comment]
> I fixed this issue in https://github.com/glebarez/sqlite Please do `go get -u github.com/glebarez/sqlite@v1.4.3` and try to reproduce.

@glebarez thanks. It works.
