### ISSUE TITLE
v1-v5,really too few

### ISSUE THREAD

**Issue by zz541843** [casbin/gorm-adapter#151]
![image](https://user-images.githubusercontent.com/72638366/160045978-e19effc8-9794-4f92-95f4-c4d160c08970.png)

**Comment by hsluoyz** [comment]
@zz541843 how many do you need?

**Comment by zz541843** [comment]
> @zz541843 how many do you need?
Add one or two more or customize

**Comment by hsluoyz** [comment]
@zz541843 let's add `v6` and `v7`, can you make a PR?
