### ISSUE TITLE
Support for postgres connection pooling

### ISSUE THREAD

**Issue by vibhugarg123** [casbin/gorm-adapter#153]
How can we add max idle connection, database max connections, database idle connections, DB connection max lifetime to postgres?
P.S-:)Using github.com/casbin/gorm-adapter/v2 v2.0.0

**Comment by hsluoyz** [comment]
@vibhugarg123 can you make a PR to expose the postgres handle public? Then you can set its value by yourself.

**Comment by vibhugarg123** [comment]
@hsluoyz  I tried creating PR against version v2.0.3. But, it's not allowing to create a PR against this tag, but allowing against master. Is it expected? If it is expected, what is the process to raise PR against particular version?
https://github.com/casbin/gorm-adapter/pull/155

**Comment by hsluoyz** [comment]
@vibhugarg123 we only develop on master (which is v3 now), can you migrate to use v3 instead?

**Comment by vibhugarg123** [comment]
@hsluoyz If I migrate to v3, I need to change in a lot of services, which would be a big change for me. It would be great if you raise it on top of v2.0.3.

**Comment by hsluoyz** [comment]
@vibhugarg123 we have released v3.x for two years. We won't maintain v2 branch any more. You can fork the v2 code and commit it by yourself.
