### ISSUE TITLE
How to turn off auto migration?

### ISSUE THREAD

**Issue by OldSmokeGun** [casbin/gorm-adapter#159]
Error 1071: Specified key was too long; max key length is 3072 bytes

One way to fix this is to change mysql's default storage engine to InnoDB, but in practice we cannot ask the DBA to do this. Another way is to change the size of the field, but this may not be able to store large field values

Please provide the option to turn off automatic migration and return the choice of whether to migrate or not to the user so that we can use the db.Set method to customize the options of the data table during automatic migration, for example:

db.Set ("gorm: table_options ", "ENGINE = InnoDB DEFAULT CHARSET = utf8mb4").AutoMigrate(model)

Now we cannot complete the automatic migration because the actions that perform the migration in the framework are after the Adapter is initialized

**Comment by OldSmokeGun** [comment]
Please provide this option! Thanks!

**Comment by hsluoyz** [comment]
@OldSmokeGun can you make a PR for it?

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
duplicate #145. To be reviewed later PR #154

**Comment by hsluoyz** [comment]
@tangyang9464 can you make a new PR based on https://github.com/casbin/gorm-adapter/pull/154 ? that PR's code quality is too bad.
