### ISSUE TITLE
table names cannot be specified after automatic migration is disabled

### ISSUE THREAD

**Issue by OldSmokeGun** [casbin/gorm-adapter#162]
#160 

This commit can indeed turn off the automatic migration, but it cannot specify a custom data table name

I try to make a commit, but I don't have the environment for unit testing, so I can't pass the test

Hope the NewAdapterWithoutAutoMigrate function can specify the data table name

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
@OldSmokeGun Because the adapter gives the user the right to create a table, the custom table name and even the table structure will be based on the functions provided by gorm itself. You can customize the table name like this
```
db, _ := gorm.Open(mysql.Open("root:root@tcp(127.0.0.1:3306)/casbin"), &gorm.Config{})
db.Table("custom_name").Migrator().AutoMigrate(&gormadapter.CasbinRule{})
a, _ := gormadapter.NewAdapterWithoutAutoMigrate(db)
```

**Comment by OldSmokeGun** [comment]
@tangyang9464 Thanks for your answer, but don't you think this limits user only can use the gormadapter.CasbinRule type?

Why can't the user's own structure and table name be passed in like the NewAdapterByDBWithCustomTable function? This is extremely scalable for users

**Comment by tangyang9464** [comment]
> @tangyang9464 Thanks for your answer, but don't you think this limits user only can use the gormadapter.CasbinRule type?
> 
> Why can't the user's own structure and table name be passed in like the NewAdapterByDBWithCustomTable function? This is extremely scalable for users

@OldSmokeGun ``db.Table("custom_name").Migrator().AutoMigrate(custom_table{})`` can define both table name and table structure. Actually ``NewAdapterByDBWithCustomTable`` also does it like this. ``CustomTable`` just change the gorm struct tags, but the table structure must stay the same. see https://github.com/casbin/gorm-adapter#customize-table-columns-example

**Comment by OldSmokeGun** [comment]
@tangyang9464 

![image](https://user-images.githubusercontent.com/30717069/168322849-4e124960-53f2-466c-82dc-9aa9314c382c.png)

As you can see, the NewAdapterWithoutAutoMigrate function uses defaultTableName, and its value is casbin_rule, which means that even if I use a custom structure when migrating, its table name must be casbin_rule, otherwise, how does the adapter know to use which table

If there are multiple casbins in a system, this will create conflicts

**Comment by OldSmokeGun** [comment]
@tangyang9464  Thanks for your contribution!

**Comment by Lee-0x00** [comment]
use **TurnOffAutoMigrate** is Fail, As follows
`db, err := gorm.Open(mysql.Open("root:ddd@tcp(127.0.0.1:3306)/test"), &gorm.Config{})
gormadapter.TurnOffAutoMigrate(db)
a, err := gormadapter.NewAdapterByDBWithCustomTable(db, nil, "casbin_rule")`
someone like me?

**Comment by tangyang9464** [comment]
> use **TurnOffAutoMigrate** is Fail, As follows
> ```golang
> db, err := gorm.Open(mysql.Open("root:ddd@tcp(127.0.0.1:3306)/test"), &gorm.Config{})      
> gormadapter.TurnOffAutoMigrate(db)       
> a, err := gormadapter.NewAdapterByDBWithCustomTable(db, nil, "casbin_rule")
> ```
> someone like me?

@Lee-0x00 db = gormadapter.TurnOffAutoMigrate(db)

**Comment by tangyang9464** [comment]
> @tangyang9464 this usage is not natural and can easily cause confusion. A call on `gormadapter.TurnOffAutoMigrate(db)` should have effect directly and it doesn't need to return a value. Can we change this behavior?

Check it out later

**Comment by tangyang9464** [comment]
> @tangyang9464 this usage is not natural and can easily cause confusion. A call on `gormadapter.TurnOffAutoMigrate(db)` should have effect directly and it doesn't need to return a value. Can we change this behavior?
