### ISSUE TITLE
How do I soft delete entries in casbin_rule table?

### ISSUE THREAD

**Issue by basimsahaf** [casbin/gorm-adapter#167]
I've been meaning to implement soft delete on my `casbin_rule` table i.e have a `deactivated_at` column that is set to the time it the policy was deleted instead of completing nuking the row from the table. This function called [here](https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L716) mentions in the documentation that if the table has a DeletedAt column, it'll perform the soft delete. So I added a new column called `deletedat` but it didn't really work 

Any ideas or tips?

**Comment by hsluoyz** [comment]
@JalinWang @imp2002 

/cc @tangyang9464

**Comment by tangyang9464** [comment]
@JalinWang @imp2002 

Maybe we should allow users to customize the table structure instead of using the default ``CasbinRule``. The current ``NewAdapterByDBWithCustomTable`` is not affordable function, we need to improve it.

**Comment by basimsahaf** [comment]
@tangyang9464 that would be great. 

The way others can make it work is that if you change the structure of `CasbinRule`, you can insert a new column (or replace any of the existing ones) called `deletedat` with type `*time.Time gorm:"column:createdat`. If gorm sees this column, it will automatically soft delete the entries without changing anything in the implementation (https://gorm.io/docs/delete.html#Soft-Delete)

**Comment by tangyang9464** [comment]
> @tangyang9464 that would be great. 
> 
> The way others can make it work is that if you change the structure of `CasbinRule`, you can insert a new column (or replace any of the existing ones) called `deletedat` with type `*time.Time gorm:"column:createdat`. If gorm sees this column, it will automatically soft delete the entries without changing anything in the implementation (https://gorm.io/docs/delete.html#Soft-Delete)

@basimsahaf This is not a generic field, so we will try to implement it through a custom structure

**Comment by basimsahaf** [comment]
@tangyang9464 yeah, I wrote that answer for others so they can make this work while you come up with a fix.

**Comment by tangyang9464** [comment]
> @tangyang9464 yeah, I wrote that answer for others so they can make this work while you come up with a fix.

@basimsahaf This is exactly what we are looking for. Unfortunately, the gorm-adapter currently does not support adding fields

**Comment by hsluoyz** [comment]
@basimsahaf you can implement and customze an adapter with soft-delete
