### ISSUE TITLE
[bug] returned data of UpdateFilteredPolicies()

### ISSUE THREAD

**Issue by JalinWang** [casbin/gorm-adapter#169]
When `Enforcer.UpdateFilteredPolicies()` is called, the calculation of effected lines require  `old rules` returned by the Adapter in `sub, obj, act` form. However, the returned data is `p, sub, obj, act`.

Traceback:
![image](https://user-images.githubusercontent.com/20621784/175821994-5d2bc77d-03c3-4657-ad81-5b1de0ebb658.png)
![image](https://user-images.githubusercontent.com/20621784/175822230-9b5d9890-c08e-44a8-bf3d-e5e6b7e01a7a.png)
![image](https://user-images.githubusercontent.com/20621784/175822030-8bb7e025-b14d-4d44-91e8-5cfe2ab39d8c.png)
![image](https://user-images.githubusercontent.com/20621784/175822033-c6e03d23-5f88-442d-9c3c-11d47fdf25d0.png)

Returned data that is unmatched with the required form(the key of policyMap ).
![image](https://user-images.githubusercontent.com/20621784/175822370-b4aab3c1-87bb-416a-8431-db9e2abd6175.png)

![image](https://user-images.githubusercontent.com/20621784/175822364-f44c10f3-275b-4327-aa44-5c7ed5f34f10.png)

**Comment by JalinWang** [comment]
I'll open a PR tomorrow

**Comment by tangyang9464** [comment]
@JalinWang see similar [casbin#1008](https://github.com/casbin/casbin/pull/1008)

**Comment by JalinWang** [comment]
Update Casbin version in `go.mod` can solve the problem.
I don't find any more similar cases.
Just close it or make a PR?

**Comment by hsluoyz** [comment]
Closed as resolved
