### ISSUE TITLE
[bug] problem about auto-migration

### ISSUE THREAD

**Issue by dayueba** [casbin/gorm-adapter#171]
main.go
```go
package main

import (
	gormadapter "github.com/casbin/gorm-adapter/v3"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)


const dsn = "root:123456@tcp(127.0.0.1:3306)/t?charset=utf8mb4&parseTime=True&loc=Local"

type User struct {
	*gorm.Model
}

func main() {
	db, _ := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	gormadapter.NewAdapterByDBWithCustomTable(db, nil, "custom_rules")
	db.AutoMigrate(&User{})
}

```
after run main.go

![image](https://user-images.githubusercontent.com/31641769/179644794-83601ccc-2b91-41dc-85fd-8c6d4af5c174.png)

table users not migrated

but when i use `gormadapter.NewAdapterByDB(db)` instead of `gormadapter.NewAdapterByDBWithCustomTable(db, nil, "custom_rules")`

it is right

![image](https://user-images.githubusercontent.com/31641769/179645159-4be3c48f-db03-4d89-b78e-f55752f195f2.png)

**Comment by JalinWang** [comment]
Can you try to drop the table and provide us a reproduction guide?

**Comment by hsluoyz** [comment]
@dayueba plz modify the original text into English, not write a new reply
