### ISSUE TITLE
MYSQL engine MyISM index maximum limit 1000

### ISSUE THREAD

**Issue by 2021-cm** [casbin/gorm-adapter#174]
When initialized the database, the MYSQL engine MyISM index maximum limit 1000 causes an error to be optimized to create the index length under the optimization

**Comment by tangyang9464** [comment]
@2021-cm You can customize the table to modify the field length. You can view README

**Comment by hsluoyz** [comment]
@2021-cm plz change to English

**Comment by 2021-cm** [comment]
When initialized the database, the MYSQL engine MyISM index maximum limit 1000 causes an error to be optimized to create the index length under the optimization

**Comment by hsluoyz** [comment]
Answered.
