### ISSUE TITLE
How do I use transaction ?

### ISSUE THREAD

**Issue by VaneLord67** [casbin/gorm-adapter#175]

**Comment by JalinWang** [comment]
@VaneLord67  Could you please provide more details about what you want to achieve (scenario&purpose) ?

**Comment by VaneLord67** [comment]
> @VaneLord67 Could you please provide more details about what you want to achieve (scenario&purpose) ?

`
common.Enforcer.Transaction(func () error {
    _, err = common.Enforcer.RemoveFilteredPolicy(0, userID, "", "")
    if err != nil {return err}
    _, err = common.Enforcer.AddPolicy(userIDStr, route, act)
    if err != nil {return err}
    return nil
}) 

`

**Comment by hsluoyz** [comment]
@VaneLord67 @JalinWang does gorm support transactions?

**Comment by VaneLord67** [comment]
> @VaneLord67 @JalinWang does gorm support transactions?

https://gorm.io/docs/transactions.html

**Comment by hsluoyz** [comment]
@JalinWang plz work on it

**Comment by VaneLord67** [comment]
@JalinWang 
I have a simple implementation at #176
