### ISSUE TITLE
[Proposal] customizability CasbinRule structure

### ISSUE THREAD

**Issue by JalinWang** [casbin/gorm-adapter#180]
Background:
Now `gorm-adapter` has `V0-V7` (introduced by https://github.com/casbin/gorm-adapter/issues/151), while other adapters have only `V0-V5`( which causes https://github.com/casbin/casbin-server/issues/71). 
Also, a request for changing back (https://github.com/casbin/gorm-adapter/issues/179 ) and a request for improving customizability ( https://github.com/casbin/gorm-adapter/issues/167 ) have been made.

Proposal:
1. Revert https://github.com/casbin/gorm-adapter/pull/157
2. [Already done] Support extra fields https://github.com/casbin/gorm-adapter/pull/168
3. Support the customized field number

**Comment by hsluoyz** [comment]
No need to put more efforts on this, see: https://github.com/casbin/gorm-adapter/issues/179#issuecomment-1228530939
