### ISSUE TITLE
flaw: dbspecified not works when specify dbname in dsn

### ISSUE THREAD

**Issue by MagicalBomb** [casbin/gorm-adapter#182]
```
// Code blow won't create database testcasbin automatically, rather than it will returns error
gormadapter.NewAdapter("mysql", "root:@tcp(127.0.0.1:3306)/testcasbin")

// Code blow works normally, but weird
gormadapter.NewAdapter("mysql", "root:@tcp(127.0.0.1:3306)/", "testcasbin")
```

**Comment by hsluoyz** [comment]
@JalinWang 

/cc @tangyang9464

**Comment by hsluoyz** [comment]
@MagicalBomb here's the docs: https://github.com/casbin/gorm-adapter#:~:text=//%20Or%20you%20can%20use%20an%20existing%20DB%20%22abc%22%20like%20this%3A%0A%09//%20The%20adapter%20will%20use%20the%20table%20named%20%22casbin_rule%22.%0A%09//%20If%20it%20doesn%27t%20exist%2C%20the%20adapter%20will%20create%20it%20automatically.%0A%09//%20a%20%3A%3D%20gormadapter.NewAdapter(%22mysql%22%2C%20%22mysql_username%3Amysql_password%40tcp(127.0.0.1%3A3306)/abc%22%2C%20true)
