### ISSUE TITLE
[bug] Resolver mysql

### ISSUE THREAD

**Issue by vine1993** [casbin/gorm-adapter#186]
When i try to use NewAdapterByDB everything explodes with drivers not related to the one that I'm using.

Im using GORM with MySQL and I've got errors related SQL server and SQlite.

**db.go**
```
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/Teknier/api/domain/user"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func DBConnection() (*gorm.DB, error) {

	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags), // io writer
		logger.Config{
			SlowThreshold: time.Second, // Slow SQL threshold
			LogLevel:      logger.Info, // Log level
			Colorful:      true,        // Disable color
		},
	)

	url := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8mb4&parseTime=True&loc=Local", "root", "root", "localhost", "3306", "test")
	db, dbErr := gorm.Open(mysql.Open(url), &gorm.Config{Logger: newLogger})

	db.AutoMigrate(&user.Entity{})

	return db, dbErr
}

```

**policy.go**

```
package main

import (
	"fmt"

	gormadapter "github.com/casbin/gorm-adapter/v3"
	"gorm.io/gorm"
)

func Policy(db *gorm.DB) {
	_, errAdapter := gormadapter.NewAdapterByDB(db)
	if errAdapter != nil {
		panic(fmt.Sprintf("failed to initialize casbin adapter: %v", errAdapter))
	}
}
```
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/2659288/195926643-05436ace-5d91-4a43-b79c-8048da448209.png">

I've already checked the DB variable and the connection work just fine, my entities migrations are working just fine.

- go version - 1.17
- casbin version - v2.56.0
- gorm version - v1.24.0
- casbin gorm adapter version - v3.11.0

**Comment by hsluoyz** [comment]
@imp2002

**Comment by imp2002** [comment]
Sorry, I cannot reproduce your error. Could you provide more code, it is best to run the reproduction directly.

**Comment by vine1993** [comment]
@imp2002 im not sure why my main project its getting this issue, I did start a new project, and did work as expected.
Thank you for checking this out, I'm closing this issue.
