### ISSUE TITLE
Adapter Transaction db table can not set

### ISSUE THREAD

**Issue by weloe** [casbin/gorm-adapter#206]
https://github.com/casbin/casbin/issues/1205
I used the registration of this business to achieve what the issue said.
https://github.com/casbin/casbin/issues/1205#issuecomment-1501221142
use `db.Exec` it works
But when I used `db.Model` or `db.Table` to set table name,it does not work,it executes table is casbin_rule
``` golang
// *request.Register has Username and Password
func Register(register *request.Register) {
	var err error
	
    // component.Enforcer type is *casbin.Enforcer
	e := component.Enforcer
	err = e.GetAdapter().(*gormadapter.Adapter).Transaction(e, func(copyEnforcer casbin.IEnforcer) error {
		// Insert to user table
		db := copyEnforcer.GetAdapter().(*gormadapter.Adapter).GetDb()
		//res := db.Exec("insert into user (username,password) values(?,?)", register.Username, register.Password)
		
               //User has Username and Password
		res := db.Table("user").Create(&User{
			Username: register.Username,
			Password: register.Password,
		})

		if err != nil || res.RowsAffected < 1 {
			return fmt.Errorf("insert error: %w", err)
		}
		// Add policy
		_, err = copyEnforcer.AddPolicy(register.Username, "resource", "write")
		if err != nil {
			return fmt.Errorf("add plocy error: %w", err)
		}
		if register.Username == "error" {
			return fmt.Errorf("register error: %w", err)
		}
		
		return nil
	})

	if err != nil {
		panic(fmt.Errorf("register error: %w", err))
	}

}

```
what it actually does is `INSERT INTO casbin_rule (usernam,password) VALUES ('','')`
I think db.Statement.scopes effect the table name, but I don't know how to resolve it

**Comment by terry-xuan-gao** [comment]
The following is my understanding, I hope it can help you.

The reason why `db.Table()` cannot execute the specified table name is this line of code：
[`a.db = db.Scopes(a.casbinRuleTable()).Session(&gorm.Session{})`](https://github.com/casbin/gorm-adapter/blob/b4efd2a92992771e08cbe264f3078aec98bd79c1/adapter.go#L367)
The default table for the current session is "casbin_rule", although you specify a different table name in the `Table()` , it does not work.

You want to operate the user table, why not use `Exec()` directly? 
`res := db.Exec("insert into user (username,password) values(?,?)", register.Username, register.Password)`
As you said,  it works.

Alternatively, you can try to create a new session, or try to modify the configuration of the current session.
