### ISSUE TITLE
policy get loaded twice

### ISSUE THREAD

**Issue by pot-code** [casbin/gorm-adapter#221]
constructor function:

```go
func NewCasbinEnforcer(db *gorm.DB) *casbin.Enforcer {
	gormadapter.TurnOffAutoMigrate(db)
	a, err := gormadapter.NewAdapterByDBWithCustomTable(db, &model.CasbinRule{}, "casbin_rules")
	if err != nil {
		panic(fmt.Errorf("error creating casbin gorm adapter: %w", err))
	}

	e, err := casbin.NewEnforcer("casbin/model.conf", a)
	if err != nil {
		panic(fmt.Errorf("error creating casbin enforcer: %w", err))
	}
	e.SetRoleManager(newRoleManager(db))
	e.EnableAutoSave(true)
	e.LoadPolicy()
	return e
}
```

logs(zerolog adapted):

```
7:36PM TRC elapsed=2.047459 rows=1 sql="SELECT * FROM `casbin_rules` ORDER BY ID"
7:36PM TRC elapsed=0.93575 rows=1 sql="SELECT * FROM `casbin_rules` ORDER BY ID"
```

if I delete `e.LoadPolicy()`, the sql will only print once

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by PokIsemaine** [comment]
In `casbin.NewEnforcer()` contains an automatic `LoadPolicy`.

The order of calls is as follows, which you can see using the IDE's debugger

1. func NewEnforcer(params ...interface{}) (*Enforcer, error)
2. e.InitWithAdapter(p0, p1.(persist.Adapter))
3. e.InitWithModelAndAdapter(m, adapter)
4. e.LoadPolicy()
5. e.adapter.LoadPolicy(newModel)

**Comment by hsluoyz** [comment]
@pot-code use `enforcer, _ := casbin.NewEnforcer()` to create an enforcer without implicit `LoadPolicy()` call
