### ISSUE TITLE
Can't call func LoadPolicy by using tablePrefix

### ISSUE THREAD

**Issue by riceChuang** [casbin/gorm-adapter#23]
first i init an enforcer by using tablePrefix
```go
cas, _ := casbin.NewEnforcer(modelPath)

adapter, err := gormadapter.NewAdapterByDBUsePrefix(db, "test_")
if err != nil {
	panic(err)
}

cas.SetAdapter(adapter)
```

then i call func cas.LoadPolicy(), that won't found any policy cuz it search db.casbin_rule
not db.test_casbin_rule

here is the code
```go
// LoadPolicy loads policy from database.
func (a *Adapter) LoadPolicy(model model.Model) error {
	var lines []CasbinRule   // this line 
	if err := a.db.Find(&lines).Error; err != nil {
		return err
	}

	for _, line := range lines {
		loadPolicyLine(line, model)
	}

	return nil
}
```

**Comment by hsluoyz** [comment]
Please send a PR.

**Comment by riceChuang** [comment]
Would it be possible to bump the version and perform a new release?

**Comment by hsluoyz** [comment]
When your PR is merged, I will bump the version and release it.

**Comment by riceChuang** [comment]
it already merge in
https://github.com/casbin/gorm-adapter/pull/24

**Comment by hsluoyz** [comment]
Released: https://github.com/casbin/gorm-adapter/releases/tag/v2.0.2
