### ISSUE TITLE
Lots of duplicate key error when running distributed casbin instances with watcher enabled

### ISSUE THREAD

**Issue by longshine** [casbin/gorm-adapter#242]
In an environment of multiple distributed casbin instances with watcher enabled, every time adding policy in one instance, it will broadcast the operation to all other instances, making them to do the add operation too. This will cause "duplicate key error" in underlying database since they are inserting one same rule at the same time.

```mermaid
sequenceDiagram
    participant Casbin-1
    participant Casbin-2
    participant DB
    Casbin-1->>DB: Add policy (p, alice, data1, read)
    DB-->>Casbin-1: OK
    Casbin-1->>Casbin-2: New policy added!
    Casbin-2->>DB: Add policy (p, alice, data1, read)
    DB-->>Casbin-2: Duplicate key error
```

To solve this issue, there is an option `OnConflict=DoNothing` to set on insert operations.

**Comment by hsluoyz** [comment]
@longshine can you make a PR to fix it?

**Comment by longshine** [comment]
Thanks!
