### ISSUE TITLE
Missing driver name in error prompt

### ISSUE THREAD

**Issue by goooogs** [casbin/gorm-adapter#244]
Databases supported by the gorm-adapter include sqlite3, but it's not shown in the error message

https://github.com/casbin/gorm-adapter/blob/6a0d216eca3b4fb6b3a57d1125b7ce92c71c3806/adapter.go#L316

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/58336abd-3783-4ca1-aa15-3b0d3946cdb2">

**Comment by hsluoyz** [comment]
@goooogs can you make a PR to fix it?
