### ISSUE TITLE
optimize tables

### ISSUE THREAD

**Issue by ffeenn** [casbin/gorm-adapter#248]
![509](https://github.com/user-attachments/assets/688d79f1-8ad7-4721-9ba3-d358315f45be)

您好，这块表名是否可以优化成从model的TableName 中获取，然而README中，自定义表名时候，并没有体现出表名变了后需要指定，或许也可以优化下README

**Comment by hsluoyz** [comment]
@ffeenn plz use English everywhere. This issue will be deleted shortly
