### ISSUE TITLE
Failure to call SavePolicy within the Transaction method when customizing table names

### ISSUE THREAD

**Issue by supuwoerc** [casbin/gorm-adapter#249]
https://github.com/casbin/gorm-adapter/blob/3d3a3c755df913a52c7077694c4b33f175a37894/adapter.go#L719-L725

https://github.com/casbin/gorm-adapter/blob/3d3a3c755df913a52c7077694c4b33f175a37894/adapter.go#L447-L464

https://github.com/casbin/gorm-adapter/blob/3d3a3c755df913a52c7077694c4b33f175a37894/adapter.go#L393-L401

Creating a tx without copying other key information causes truncate table to fail to find the table name。

**Comment by supuwoerc** [comment]
```go
	//adapter, err := gormadapter.NewAdapterByDBUseTableName(db, TablePrefix, "casbin")
	adapter, err := gormadapter.NewAdapterByDB(db)
```

I tried not setting a custom database table name, but the error persists, and debugging revealed that the tableName is not copied either!

**Comment by Hill1126** [comment]
same problem with me

**Comment by ypli0629** [comment]
@hsluoyz The problem has occurred again.

**Comment by ypli0629** [comment]
https://github.com/casbin/gorm-adapter/blob/b821ccde9c8662ed76ebd02acc5ecf0dc5a156f9/adapter.go#L768
