### ISSUE TITLE
[Question] : Can version mismatch cause this particular issue ??

### ISSUE THREAD

**Issue by shrutsureja** [casbin/gorm-adapter#254]
i have this issue mentioned in detail over here https://github.com/casbin/casbin/issues/1459

what i also observed is that i gorm-adapter uses the casbin version of `v2.77.1` https://github.com/casbin/gorm-adapter/blob/16aa5026dcec03b290ff44401a5d2957521d777f/go.mod#L6  and the latest version of casbin is `v2.100.0` and i am using the latest casbin version 

so can this version mismatch cause the nil pointer reference  ?? issue linked above

**Comment by shrutsureja** [comment]
One more question is that can i use this type of custom table ? one more v6 column in the field i need this for the effects !!

i have linked the casbin issue above it has my model 

```golang
type Authorization_rules struct {
	ID    uint   `gorm:"primaryKey;autoIncrement"`
	Ptype string `gorm:"size:512;uniqueIndex:unique_index"`
	V0    string `gorm:"size:512;uniqueIndex:unique_index"`
	V1    string `gorm:"size:512;uniqueIndex:unique_index"`
	V2    string `gorm:"size:512;uniqueIndex:unique_index"`
	V3    string `gorm:"size:512;uniqueIndex:unique_index"`
	V4    string `gorm:"size:512;uniqueIndex:unique_index"`
	V5    string `gorm:"size:512;uniqueIndex:unique_index"`
	V6    string `gorm:"size:512;uniqueIndex:unique_index"`
}
```

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/gorm-adapter/commit/6479a483c7dc725e5270ba059ba17bbd9ceeda44

**Comment by shrutsureja** [comment]
@hsluoyz can we use more than v5, like v6,v7 if we need to using the gorm adapter ?

**Comment by hsluoyz** [comment]
@shrutsureja fork it and change by yourself
