### ISSUE TITLE
Hardcoded "postgres" string DB in function openDBConnection() causes table being created in the DB named "postgres"

### ISSUE THREAD

**Issue by 16pj** [casbin/gorm-adapter#48]
Sorry I'm new to creating issues here.

file: adapter.go
version tag: 3.02

If the a.dbSpecified is set to true then isn't it expected to use the db name specified in the datasource string, but looks like the hardcoded value "postgres" in openDBConnection() [adapter.go] makes it override the db and uses "postgres" instead.

**Comment by hsluoyz** [comment]
@16pj can you make a PR to fix it?

@nodece @GopherJ @00LT00

**Comment by 00LT00** [comment]
Sorry, I forgot. You can add "dbname=xxx" to dsn in order to use normally before I fix this bug. @16pj

**Comment by 16pj** [comment]
> Sorry, I forgot. You can add "dbname=xxx" to dsn in order to use normally before I fix this bug. @16pj

I use dbname but it gets overridden by "dbname=postgres".

**Comment by 00LT00** [comment]
> > Sorry, I forgot. You can add "dbname=xxx" to dsn in order to use normally before I fix this bug. @16pj
> 
> I use dbname but it gets overridden by "dbname=postgres".

Can you tell me where has "dbname=postgres" ?

**Comment by nodece** [comment]
@16pj could you provide your code?
