### ISSUE TITLE
gorm-adapter's DefaultTableNameHandler

### ISSUE THREAD

**Issue by stevemilk** [casbin/gorm-adapter#5]
When I use gorm-adapter's DefaultTableNameHandler to add a prefix name to each table, casbin's default table "casbin_rule" cannot be used to remove a policy.
That's because casbin_rule has no primary key, and policy's remove action is different from add action . I tried to init gorm-adapter in front of DefaultTableNameHandler, it still not woked.
Finially, I change casbin's default table name "casbin_rule" to "$prefix_casbin_rule", and make a judgement in DefaultTableNameHandler : if table name is equal to "$prefix_casbin_rule", prefix name will not be added .
If you any better solution , welcome to reply to me~

**Comment by hsluoyz** [comment]
I think maybe you can modify the code here: 

https://github.com/casbin/gorm-adapter/blob/e56c6daebd5e8c657caf3bdf3a647803cf7b242d/adapter.go#L37-L39

Return a table name with your prefix.

**Comment by hsluoyz** [comment]
Closed as stale.
