### ISSUE TITLE
NewAdapterByDB  failed due to different gorm type

### ISSUE THREAD

**Issue by kevinniu666** [casbin/gorm-adapter#55]
tried to use exsit gorm instance which is "github.com/jinzhu/gorm", failed due to below error:

Cannot use 'component.DB' (type *"github.com/jinzhu/gorm".DB) as type *"gorm.io/gorm".DB 

//code sample

adapter, err := gormadapter.NewAdapterByDB(component.DB)

**Comment by hsluoyz** [comment]
`github.com/jinzhu/gorm` path is deprecated. Please update it to use `gorm.io/gorm` instead.
