### ISSUE TITLE
How to set custom column size?

### ISSUE THREAD

**Issue by Gaadek** [casbin/gorm-adapter#56]
Hello,

First of all, thank you for this project, it's very useful.

I'm using casbin with a RESTful model, i.e. the list of permissions for a given roles are strored in 1 record in the dabatase (vs 1 record per permissions/role as usualy) : 

Instead of this :
`p, data2_admin, data2, read
p, data2_admin, data2, write`

I'm using this : 
`p, data2_admin, data2, (read)|(write)`

The problem is that my casbin gorm adapter defines the column size without any option to adapt it as per end user needs : 
```
V0    string `gorm:"size:40;uniqueIndex:unique_index"`
V1    string `gorm:"size:40;uniqueIndex:unique_index"`
V2    string `gorm:"size:40;uniqueIndex:unique_index"`
V3    string `gorm:"size:40;uniqueIndex:unique_index"`
V4    string `gorm:"size:40;uniqueIndex:unique_index"`
V5    string `gorm:"size:40;uniqueIndex:unique_index"`
```

Is there something that drives this decision or can we imagine to change that?

Thanks

**Comment by hsluoyz** [comment]
Can you make a PR to fix it? @nodece

**Comment by hsluoyz** [comment]
@Gaadek what do you want?

**Comment by Gaadek** [comment]
@hsluoyz I'd like to be able to set the size of the fields as per my needs.

In my specific case, it's the length of v3 that is too small.

**Comment by hsluoyz** [comment]
As I see it, it's not possible to specify a dynamic size for it. Tell me if I'm wrong.

If this is the case, what length do you think is enough?

**Comment by nodece** [comment]
We can use the `reflect` to set the size of the fields, it will cause `reflect` everywhere.

**Comment by hsluoyz** [comment]
reflect everywhere is not good. I prefer a bigger static size. @Gaadek give a static number?

**Comment by nodece** [comment]
@hsluoyz can struct tag support the use of variables?

**Comment by hsluoyz** [comment]
@nodece I think this is impossible: https://stackoverflow.com/questions/29752462/go-struct-using-a-variable-in-the-struct-tag

**Comment by Gaadek** [comment]
Thank for your searches and the discussion.

After thinking about it, I believe the most appropriate approach would be to use gorm to update the columns.
We should be able to call NewAdapter of gorm-adapter, then gorm to update the length of any columns of the casbin rule table.

**Comment by Gaadek** [comment]
in the case of, here is how I manage that:

#01 : Declare a model for the CasbinRules  (gorm adapter uses CasbinModel, so use the same model name) :
```go
type CasbinRule struct {
	gormadapter.CasbinRule
	
	// Override the default model definition
	V3 string `gorm:"size:1000"`
}
```

#02 : Define a logic to build/rebuild the CasbinRule table. I use here a boolean stored in my config  :
```go
if cfg.RebuildCasbinTable {
	if db.Migrator().HasTable(&CasbinRule{}) {
		db.Migrator().DropTable(&CasbinRule{})
	}
}
```

#03 : Build the CasbinRule table based on our custom local model : 
```go
db.Migrator().CreateTable(&CasbinRule{})
```

#04 : Finally, call the NewAdapterFromDB : 
```go
casbinAdapter, _ := gormadapter.NewAdapterByDB(db)
```

Note: you must **not** use anymore the `c.CasbinEnforcer.SavePolicy()` which drops and recreates the CasbinRule table... But Gorm adapter has an autosave feature that makes this SavePolicy call useless (at least in my case)

**Comment by StianOvrevage** [comment]
Custom column length might not be necessary. But the default of 40 seems low.

I for example cannot use `company:e39c919e-ce66-4c5f-3631-14d635a3a33d` as an identifier. That long part is a standard UUID that many uses for many different things.

**Comment by hsluoyz** [comment]
@StianOvrevage we just increased the custom column size back to 100, see: https://github.com/casbin/gorm-adapter/issues/63

**Comment by StianOvrevage** [comment]
What a stroke of luck! Thanks so much :)

**Comment by realpg** [comment]
> Custom column length might not be necessary. But the default of 40 seems low.
> 
> I for example cannot use `company:e39c919e-ce66-4c5f-3631-14d635a3a33d` as an identifier. That long part is a standard UUID that many uses for many different things.

It's not 40 now.
It's 100.
But I want to change it back to 40.
Due to mysql innodb with 4k page_size, index of utf8mb4 varchar must be less than 47.

**Comment by hsluoyz** [comment]
@realpg I'm not going to set it to 40 and then make it back to 100 back and forth. You use a version that has 40, or you fork it and modify it by yourself.
