### ISSUE TITLE
mysql 创建的数据库的表名是casbin_rules 

### ISSUE THREAD

**Issue by smartisantt** [casbin/gorm-adapter#57]
使用github.com/casbin/gorm-adapter/v3 v3.0.3   的时候 ， 

`
	if !db.Migrator().HasTable("casbin_rule") {
		err = db.Migrator().CreateTable(&gormadapter.CasbinRule{})
	}
`
mysql 创建的数据库的表名是casbin_rules  ，应该是 casbin_rule 才能正常使用

**Comment by hsluoyz** [comment]
@nodece

**Comment by hsluoyz** [comment]
@smartisantt can you please change your title and text into English? Thanks!

**Comment by smartisantt** [comment]
OK, It's my wrong. There is no question.😊
