### ISSUE TITLE
unknown field 'WithConditions' in struct literal of type gorm.Session

### ISSUE THREAD

**Issue by twhit-mrwebapps** [casbin/gorm-adapter#58]
Hi,

I'm attempting to import your adaptor into my project, however I am getting the following message:

/home/tim/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.0.3/adapter.go:247:25: unknown field 'WithConditions' in struct literal of type gorm.Session

Do you know what the issue might be?

**Edit**: You may notice I closed, then reopened, I immediately thought that it was related to the wrong version of gorm installed. However upon further testing it still occurs as the gorm.Session does not appear to have WithConditions, wondering if they may have been a recent update in gorm?

**Comment by twhit-mrwebapps** [comment]
* Fixed, I was using the wrong gorm package.

**Comment by nodece** [comment]
I'm not sure that your gorm version. The adapter are using `gorm.io/gorm v1.20.1`.

**Comment by twhit-mrwebapps** [comment]
Latest I believe which is https://github.com/go-gorm/gorm v1.20.7

**Comment by nodece** [comment]
@twhit-mrwebapps I guess they're constantly upgrading. could you use `gorm@1.20.1` in your project?

**Comment by twhit-mrwebapps** [comment]
Already have, thanks for that. I'll keep an eye on your pull request.

**Comment by hsluoyz** [comment]
Gorm v1.20.7 removed `WithConditions`, see: https://github.com/go-gorm/gorm/issues/3768

**Comment by hsluoyz** [comment]
@twhit-mrwebapps is there any reason that we should update gorm to v1.20.7 ?

**Comment by twhit-mrwebapps** [comment]
No reason to upgrade to my knowledge. I was starting a new project with the latest version and this is what I came across. Thought it might be worthy to investigate. Not sure if Gorm was intending to remove it or perhaps by accident. Not urgent as I'm using a previous version. Having said that, if Gorm is seeking to change struct variables, I suppose you need to update at the end of the day so yeah.

**Comment by cqasen** [comment]
请问一下，这个更新，什么时候能出新的tag呢

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/gorm-adapter/pull/59

**Comment by hsluoyz** [comment]
@nodece @00LT00

**Comment by nodece** [comment]
@cqasen @twhit-mrwebapps v3.0.4 has been released.
