### ISSUE TITLE
Column size

### ISSUE THREAD

**Issue by Despire** [casbin/gorm-adapter#63]
Hi, I'm migrating to new gormadapter, And it seems that the column size was lowered to [40](https://github.com/casbin/gorm-adapter/blob/master/adapter.go#L38) from the original [100](https://github.com/casbin/gorm-adapter/blob/9cc32f0fb415e9bb5bf152a2f8e06aa6f2d65ad2/adapter.go#L34). I was wondering if it would be possible to bump up the size back to  100?

 (As I have problems now when I'm migrating it 'cause of the size differences.)

**Comment by hsluoyz** [comment]
@Despire can you make a PR to fix it?

**Comment by Despire** [comment]
@hsluoyz sure

**Comment by hsluoyz** [comment]
@Despire released v3.0.5: https://github.com/casbin/gorm-adapter/releases/tag/v3.0.5
