### ISSUE TITLE
gormadapter.Adapter is not persist.UpdatableAdapter: missing method UpdatePolicy

### ISSUE THREAD

**Issue by typhoonbb** [casbin/gorm-adapter#71]
*gormadapter.Adapter is not persist.UpdatableAdapter: missing method UpdatePolicy
how to fix this ?  thank you

here is go.mod:
github.com/casbin/casbin/v2 v2.20.2
github.com/casbin/gorm-adapter/v3 v3.0.5
gorm.io/gorm v1.20.7

**Comment by hsluoyz** [comment]
@typhoonbb we fixed it in v3.0.6 (https://github.com/casbin/gorm-adapter/issues/65)

Plz update it to latest v3.1.0
