### ISSUE TITLE
custom column size  support

### ISSUE THREAD

**Issue by Despire** [casbin/gorm-adapter#72]
Hi, I was wondering if there are any plans to support custom column sizes? I've reached a use-case where the 100 column size limit is not sufficient.

I noticed there was an Issue opened about this #56, however, the solution wouldn't work for me, as I'm using cockroach and get this error 
```
ALTER TABLE "casbin_rule" ALTER COLUMN "v0" TYPE varchar(100);
ERROR: unimplemented: type conversion not yet implemented
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/9851
```

One solution (somewhat hacky though) that could work is, that we could pass a custom `CasbinRule` table in the DB context and used that instead of the default `CasbinRule`, [example](https://github.com/Despire/gorm-adapter/blob/custom_column_size/adapter.go#L82-L95), and when creating the table we could just use the [custom one](https://github.com/Despire/gorm-adapter/blob/custom_column_size/adapter.go#L298-L305)

What do you think about this ?

**Comment by hsluoyz** [comment]
@Despire what's your desired column size?

**Comment by Despire** [comment]
@hsluoyz as of now I would need 512

**Comment by hsluoyz** [comment]
@Despire I'm OK with your idea. But we should follow:

1. Be compatible with the original usage, so other people won't be affected.
2. We can add additional constructor to support a custom table.
3. Add the new API to README, to allow others to use it.

If this is OK, plz make a PR, thanks!

**Comment by Despire** [comment]
@hsluoyz Ok I'll work on it.

**Comment by hsluoyz** [comment]
@Despire thanks for the PR! Released: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.0
