### ISSUE TITLE
[Question] Customizing casbin_rule table name

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#74]
**What's your scenario? What do you want to achieve?**
We are working on a cloud based offering and planning to use casbin.
In that we would like to segregate tenant's data and for that we would like to create separate casbin_rules tables for each tenant. 
I know that we have the provision for seperate databases and that we can pass in the connection string
But we don't want to have that many databases.

So our requirement is that instead of the default table name casbin_rule how can we have that table name customized to something like tenant1_casbin_rule, tenant1_casbin_rule... tenantn_casbin_rule

**Comment by hsluoyz** [comment]
@arafat-java see:

https://github.com/casbin/gorm-adapter/blob/d4ad5d9aa5106ca2d6d979b195ea08d1c06c8fdd/adapter.go#L158-L177
