### ISSUE TITLE
Behaviour of NewAdapterByDB() has a breaking change

### ISSUE THREAD

**Issue by d1ss0nanz** [casbin/gorm-adapter#78]
Hi,

Just a heads up for other users: 
I've updated from gorm-adapter 3.0.3 to 3.2.0 today and found that NewAdapterByDB() is now using "casbin_rule" as table name vs. "casbin_rules" in 3.0.3.

Therefore the user group memberships where missing in the new "casbin_rule" table.

The reason is probably (didn't verify) the use of the Gorm Migrator in 3.0.3: 	
`return a.db.Migrator().CreateTable(a.getTableInstance())`
In Gorm "CasbinRule" will result in a table name "casbin_rules".

This fixed if for me:
` insert into casbin_rule(ptype,v0,v1) select p_type,v0,v1 from casbin_rules where p_type = 'g';`

**Comment by hsluoyz** [comment]
@d1ss0nanz I think `casbin_rule` has always been the rule name? Even before v3.0.3, we have:

![image](https://user-images.githubusercontent.com/3787410/108714675-ceabcb80-7554-11eb-81da-c47f1ee2e0c1.png)

**Comment by d1ss0nanz** [comment]
Yes, but that's not the cause. I've checked my old logs and my database initialisation scripts.
It was "casbin_rules" in 3.0.3.

Please see my note about the use of the Migrator.

**Comment by hsluoyz** [comment]
> The reason is probably (didn't verify) the use of the Gorm Migrator in 3.0.3:
return a.db.Migrator().CreateTable(a.getTableInstance())
In Gorm "CasbinRule" will result in a table name "casbin_rules".

@closetool is it possible to fix this bug?

**Comment by closetool** [comment]
In v3.0.3 NewAdapterByDB will create table named `casbin_rules`, because of this
![image](https://user-images.githubusercontent.com/52988625/108791438-0ac54780-75ba-11eb-9e2b-5bcff8d61847.png)
And NewAdapter will create table named `casbin_rules`

In v3.2.0 they both create table named `casbin_rule`,
I think it works fine now, nothing needed to change.

**Comment by closetool** [comment]
@d1ss0nanz What can I do for you?

**Comment by hsluoyz** [comment]
@closetool if someone is running our migration code (the following line):

```go
return a.db.Migrator().CreateTable(a.getTableInstance())
```

Will they end up with the wrong table name: `casbin_rules` ?

**Comment by closetool** [comment]
@hsluoyz In v3.2.0, there will be no casbin_rules default, in spite of that, I change the `CasbinRule`'s name mapping

**Comment by d1ss0nanz** [comment]
Ok, so up to at least 3.0.3, in some code paths, the created table is named "casbin_rules".
NewAdapterByDB() is behaving this way in 3.0.3.

Now, when updating to a more recent version, gorm-adapter is creating a new table "casbin_rule" besides the fact that there already exists a table "casbin_rules".

All authorization attempts silently fail, since the group membership data is in the old table.

I would suggest that you document the breaking change, so one doesn't have to understand how Gorm derives table names from struct names, to understand what's going on.

Optionally, there should be migration code that checks for a table "casbin_rules" and moves the data over when creating "casbin_rule".

**Comment by 00LT00** [comment]
@hsluoyz @closetool Hello, I think it was a new bug with new version gorm.
We use the scopes function to realize the dynamic table name. like this
```go
        a.db = db.Scopes(a.casbinRuleTable()).Session(&gorm.Session{})
	err := a.createTable()
```
It was successful work at least version 1.20.8.
But now, even if we use this version too, new users also will use new version gorm, which make us have to use new version to run. I'm already asking the author this bug at [here](https://github.com/go-gorm/gorm/issues/4145#issuecomment-795444810). I think it's necessary to remind users on the readme.md before the author has a new reply.

**Comment by closetool** [comment]
@00LT00 @hsluoyz I noticed we have run up some commits from last releasing new version
In #79, I added `default table name` function, and I believe it will work even if scope failed.

**Comment by 00LT00** [comment]
@closetool  But I get the same error, why?
If I update the version of gorm on `go.mod`, it was work. I think it was a bug of gorm rather than ours

**Comment by 00LT00** [comment]
> @00LT00 For me this was caused by using `NewAdapterByDB(db)` and from looking at the code I assume that `NewAdapterByDBUseTableName(db, "", "casbin_rules")` should do the trick.
> 
> But I've decided to just migrate the data into "casbin_rule" and go with the default.

It just fix your error, but the bug is there.

**Comment by 00LT00** [comment]
hi @closetool I know why....
The latest version 3.2.0 did not import your changes. So we should release a new version for #79 ... @hsluoyz

**Comment by closetool** [comment]
@00LT00 yep

**Comment by 00LT00** [comment]
But it just fix the defalt table names. If user use dynamic table name, and the table is not exist. Then the table will not be create.
![image](https://user-images.githubusercontent.com/47566260/110650625-adeea180-81f5-11eb-92c9-303e3bfada8c.png)
So I still suggest we should remind user that not update version of gorm at least `1.20.12` .

**Comment by hsluoyz** [comment]
@00LT00 thanks! I saw Jinzhu has fixed that bug. So updating to Gorm master HEAD will fix the issue.

Bug fixed in: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.2
