### ISSUE TITLE
The default automatically created table is “casbin_rules“, but the default selected table is “casbin_rule“

### ISSUE THREAD

**Issue by shaolei** [casbin/gorm-adapter#80]
![image](https://user-images.githubusercontent.com/3926839/110626454-b33ef280-81db-11eb-9ff6-07bae8e40fc4.png)

**Comment by hsluoyz** [comment]
Hi @shaolei can you modify your text into English?

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@shaolei Hi, could you provide some more specific infos, cause I test locally and it works well
![image](https://user-images.githubusercontent.com/52988625/110639661-ef2d8400-81ea-11eb-8099-9a5a28b24c53.png)

**Comment by 00LT00** [comment]
@shaolei hello. I suggest you could change the version of gorm on go.mod. It runs correctly

**Comment by hsluoyz** [comment]
@shaolei bug fixed in: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.2
