### ISSUE TITLE
Error 1071: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by OldSmokeGun** [casbin/gorm-adapter#84]
[7.557ms] [rows:0] CREATE UNIQUE INDEX idx_casbin_rule ON casbin_rule (ptype,v0,v1,v2,v3,v4,v5)
panic: Error 1071: Specified key was too long; max key length is 1000 bytes

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@OldSmokeGun Hi, it's not the adapter's fault, it caused by mysql, perhaps you used MyISAM engine instead of innodb, plz refer to https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

**Comment by hsluoyz** [comment]
@closetool just see your link: https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes

![image](https://user-images.githubusercontent.com/3787410/111324299-9d32a580-86a5-11eb-9c92-8d119e8c7809.png)

Can we just index the prefix of the columns, so make them sum up to < 1000? So even if the user has a very long subject or object to store, he will not encounter this error.

**Comment by OldSmokeGun** [comment]
@closetool  Sir, thank you for your reply, this problem has been solved, I like casbin
