### ISSUE TITLE
NewAdapterByDBUseTableName does not create table with custom name

### ISSUE THREAD

**Issue by thnt** [casbin/gorm-adapter#90]
`NewAdapterByDBUseTableName(db, "", "casbin_rules")` will create table with default name `casbin_rule` but tries to create index for table `casbin_rules` and return an error: 

`ERROR: relation "casbin_rules" does not exist (SQLSTATE 42P01)`

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@thnt Which version are you using? Plz use v3.2.3 and ensure you not import gorm with version over 1.20.x

**Comment by thnt** [comment]
```
gorm.io/gorm v1.21.3
github.com/casbin/gorm-adapter/v3 v3.2.3
```

The similar bug: `NewAdapterByDBWithCustomTable(db, &MyRule{})` will create table `my_rules` but it will try to create index for default table name `casbin_rule`

**Comment by closetool** [comment]
@thnt fixed, plz review
And do not use gorm v1.21.x if possible

**Comment by zsnivy** [comment]
> plz review #91

This commit has solved the problem of not creating the index to the custom table, but the problem of not creating the specified table by `NewAdapterByDBUseTableName` function still exists.
example:
1. i specified the table name. `NewAdapterByDBUseTableName(db, "f", "ac_policy")`
2. but in the `createTable` function:
``` go
func (a *Adapter) createTable() error {
	t := a.db.Statement.Context.Value(customTableKey{}) // t will get nil

	if t != nil {
		return a.db.AutoMigrate(t)
	}

	t = a.getTableInstance() // t will get &CasbinRule{}
	if err := a.db.AutoMigrate(t); err != nil { // gorm will auto create table "casbin_rule"
		return err
	}

	tableName := a.getFullTableName()
	index := "idx_" + tableName
	hasIndex := a.db.Migrator().HasIndex(t, index) // gorm will find that there is no specified index in the table of "casbin_rule"
	if !hasIndex { // It will then create an index into the custom table "f_ac_policy" 
		if err := a.db.Exec(fmt.Sprintf("CREATE UNIQUE INDEX %s ON %s (ptype,v0,v1,v2,v3,v4,v5)", index, tableName)).Error; err != nil {
			return err
		}
	}
	return nil
}
```

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@zsnivy I tried with `gorm 1.21.4`  & `gorm 1.20.7`, and adapter works fine with `gorm 1.20.7`, plz do not use `gorm 1.21.x`

**Comment by zsnivy** [comment]
> adapter works fine with `gorm 1.20.7`, plz do not use `gorm 1.21.x`

Thanks for your answers, the problem has been solved.
