### ISSUE TITLE
postgres - won't detect whether database exists

### ISSUE THREAD

**Issue by kuchaguangjie** [casbin/gorm-adapter#95]
**Repeated database creation:**
---

It will still trying create the database, even I have specified `dbname=casbin` in gorm dsn:
> github.com/casbin/gorm-adapter/v3@v3.2.6/adapter.go:237 ERROR: database "casbin" already exists (SQLSTATE 42P04)

Better create only if not exists yet, I guess.

BTW, the 2nd issue about timezone is moved to: https://github.com/casbin/gorm-adapter/issues/96

**Comment by hsluoyz** [comment]
@kuchaguangjie hi, thanks for your bug report! Can you put the 2nd bug to another issue?

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@kuchaguangjie For the first issue, plz see below
![image](https://user-images.githubusercontent.com/52988625/115716902-44dd7a80-a3ac-11eb-9e71-75ba0a497afe.png)

**Comment by closetool** [comment]
@kuchaguangjie For the first issue, plz see below
![image](https://user-images.githubusercontent.com/52988625/115717164-7d7d5400-a3ac-11eb-903e-9817b526390c.png)

**Comment by closetool** [comment]
@kuchaguangjie For the second issue, plz just use lower case...
![image](https://user-images.githubusercontent.com/52988625/115718453-b36f0800-a3ad-11eb-9f87-7407cff9864c.png)

**Comment by hsluoyz** [comment]
@closetool see: https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL

![image](https://user-images.githubusercontent.com/3787410/115720560-c2ef5080-a3af-11eb-9e68-79791fc4cf08.png)

**Comment by closetool** [comment]
@hsluoyz In official docs, `TimeZone` was used https://www.postgresql.org/docs/9.2/datatype-datetime.html#DATATYPE-TIMEZONES.
But I tested `timezone` and it works.
Could you please try it @kuchaguangjie ?

**Comment by kuchaguangjie** [comment]
@hsluoyz Moved the 2nd issue to: https://github.com/casbin/gorm-adapter/issues/96

**Comment by kuchaguangjie** [comment]
@hsluoyz Thanks, for the db creation issue, after add 3rd param as `true` in `NewAdapter()`, and specify dbname in gorm dsn, now it won't create db.

Code:

```
    dsn := "host=localhost user=postgres password=mypswd port=5432 dbname=casbin sslmode=disable"
    a, _ := gormadapter.NewAdapter("postgres", dsn, true)
    ef, _ := casbin.NewEnforcer("/path/to/rcba_model.conf", a)
```

**Comment by xuanlongvts** [comment]
> @hsluoyz Thanks, for the db creation issue, after add 3rd param as `true` in `NewAdapter()`, and specify dbname in gorm dsn, now it won't create db.
> 
> Code:
> 
> ```go
>     dsn := "host=localhost user=postgres password=mypswd port=5432 dbname=casbin sslmode=disable"
>     a, _ := gormadapter.NewAdapter("postgres", dsn, true)
>     ef, _ := casbin.NewEnforcer("/path/to/rcba_model.conf", a)
> ```

Just add true parameter in the last. It's fine.
