### ISSUE TITLE
postgres - can't set timezone

### ISSUE THREAD

**Issue by kuchaguangjie** [casbin/gorm-adapter#96]
-------

**Can't set timezone:**
---

If I specify `TimeZone=Asia/Shanghai` in gorm dsn, then will get error:

> 2021/04/22 19:06:44 /home/eric/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.2.6/adapter.go:214
> [error] failed to initialize database, got error failed to connect to `host=localhost user=postgres database=casbin`: server error (FATAL: invalid value for parameter "TimeZone": "Asia/Shanghai dbname=casbin" (SQLSTATE 22023))
> model conf: /home/eric/go/src/gitlab.com/kuchaguangjie/go-learn/casbin/adapter/gorm/conf/rbac_model.conf
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8ca865]
> 
> goroutine 1 [running]:
> github.com/casbin/gorm-adapter/v3.(*Adapter).IsFiltered(0x0, 0x7fce8af15340)
>         /home/eric/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.2.6/adapter.go:396 +0x5
> github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc00042e100, 0xc00021b770, 0x7fce8af15340, 0x0, 0x0, 0x7fce8af15340)
>         /home/eric/go/pkg/mod/github.com/casbin/casbin/v2@v2.28.0/enforcer.go:168 +0x142
> github.com/casbin/casbin/v2.(*Enforcer).InitWithAdapter(0xc00042e100, 0xc00010e660, 0x5c, 0x7fce8af15340, 0x0, 0x7fce8aeff700, 0x8)
>         /home/eric/go/pkg/mod/github.com/casbin/casbin/v2@v2.28.0/enforcer.go:146 +0x7b
> github.com/casbin/casbin/v2.NewEnforcer(0xc00017df58, 0x2, 0x2, 0x99e79c, 0x4, 0x9a1072)
>         /home/eric/go/pkg/mod/github.com/casbin/casbin/v2@v2.28.0/enforcer.go:95 +0x36b
> 

But according to [gorm postgres doc](https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL), it's valid dsn syntax.

BTW, since this issue is migrated from another, it already got some useful comment:
https://github.com/casbin/gorm-adapter/issues/95#issuecomment-824819864

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/gorm-adapter/issues/95#issuecomment-824848401

**Comment by kuchaguangjie** [comment]
@hsluoyz Thanks, for the db creation issue, after add 3rd param as `true` in `NewAdapter()`, and specify dbname in gorm dsn, now it won't create db.

Code:

```
    dsn := "host=localhost user=postgres password=mypswd port=5432 dbname=casbin sslmode=disable"
    a, _ := gormadapter.NewAdapter("postgres", dsn, true)
    ef, _ := casbin.NewEnforcer("/path/to/rcba_model.conf", a)
```

**Comment by kuchaguangjie** [comment]
@hsluoyz I just tested on another laptop that both `TimeZone` and `timezone` works, seems case doesn't matter.

In my 2nd laptop I initially get error:

> go: myrepo/casbin/adapter/gorm: package gorm.io/driver/postgres imported from implicitly required module; to add missing requirements, run:
> 	go get gorm.io/driver/postgres@v1.0.1

Then I run:
> go get gorm.io/driver/postgres

And get:
> go get: upgraded gorm.io/driver/postgres v1.0.1 => v1.0.8

Then when I run the program, the issue in question didn't occur, no matter whether or how I specify timezone.
Maybe it's due to driver issue ? On my first laptop, the implicit `gorm.io/driver/postgres` is too old ? (Which was `gorm.io/driver/postgres v1.0.1` I think).

**Comment by kuchaguangjie** [comment]
I tested the older `gorm.io/driver/postgres` version via:
> go get gorm.io/driver/postgres@v1.0.1

The issue didn't occur either ... Now sure how the issue occur on first laptop now, I can't test it now.
Maybe due to postgres server version? The 2nd laptop use pg **12.5**, the 1st uses pg **13**, not sure is that an issue.

**Comment by hsluoyz** [comment]
@kuchaguangjie this repo uses: https://github.com/go-gorm/postgres , you can also send an issue to them for more guidance.

**Comment by kuchaguangjie** [comment]
@hsluoyz I did more test on 1st machine, which use pg `13.0`.

The error occur when use combination of `gorm.io/driver/postgres@v1.0.1` and `TimeZone` and `pg 13.0`.

The issue can be fixed by any of following change:

- Use lowercase `timezone` instead of `TimeZone`.
- Upgrade to `gorm.io/driver/postgres@v1.0.8`.
- Downgrade pg to `12.5`.

So, it probably is due to pg driver & pg server version issue.

**Comment by hsluoyz** [comment]
@closetool plz update it:

https://github.com/casbin/gorm-adapter/blob/fa4239f79114122142bce7dfe60c09f8eef5c741/go.mod#L12
